### ISSUE TITLE
Javaを8から11に上げた時、Eclipse上での注釈処理が遅くなる

### ISSUE THREAD

**Issue by inoue-koki** [domaframework/doma#1024]
**Describe the bug**
`sourceCompatibility` `targetCompatibility` を `1.8` から `11` に上げた後、
Eclipseからビルドを行った時、注釈処理にかかる時間が大きく伸びてしまいました。
処理時間を少しでも減らしたいのですが解決の糸口が分からず、分かることがあれば教えていただけないでしょうか？

**Expected behavior**
1.8の時、`doma.debug=true` を設定し、Eclipseのログファイルから処理時間を集計しました。
| プロセッサ | 個数 | 平均時間(ミリ秒) | 合計時間(ミリ秒) | 
|----------|------|---------------|----------------|
| org.seasar.doma.internal.apt.processor.DaoProcessor | 676 | 9.7 | 6578 |
| org.seasar.doma.internal.apt.processor.DomainProcessor | 7 | 3.4 | 24 |
| org.seasar.doma.internal.apt.processor.EntityProcessor | 1534 | 1.4 | 2191 |
| org.seasar.doma.internal.apt.processor.SingletonConfigProcessor | 1 | 1 | 1 |

**Actual behavior**
11の時にも、同様の方法で集計しました。
| プロセッサ | 個数 | 平均時間(ミリ秒) | 合計時間(ミリ秒) | 
|----------|------|---------------|----------------|
| org.seasar.doma.internal.apt.processor.DaoProcessor | 676 | 539.5 | 364730 |
| org.seasar.doma.internal.apt.processor.DomainProcessor | 7 | 15.5 | 109 |
| org.seasar.doma.internal.apt.processor.EntityProcessor | 1534 | 53.2 | 81711 |
| org.seasar.doma.internal.apt.processor.SingletonConfigProcessor | 1 | 3 | 3 |

**To Reproduce**
1. build.gradle の `sourceCompatibility` `targetCompatibility` を変更する。
2. Eclipseから「Gradle > Refresh Gradle Project」を行う。
3. Eclipseから「Project > Clean... > Start a build immediately」を行う。

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
- Doma version or git rev: 2.54.2
- IDE version (ie. Eclipse or IntelliJ IDEA): Eclipse 2023-09
- Output of `java -version`:
  - 旧: OpenJDK Runtime Environment (Temurin)(build 1.8.0_382-b05)
  - 新: OpenJDK Runtime Environment Temurin-11.0.20.1+1 (build 11.0.20.1+1)
- Build tool (ie. output of `mvnw --version` or `gradlew --version`): 7.6.3
- Database version: N/A
- JDBC Driver version: N/A

**Additional context**
* ターミナルから直接 `./gradlew build` を行った際は、`1.8`, `11`ともに処理時間は変わりませんでした。
  このため、Eclipseの問題である気はしています。
* Eclipseのバージョンを落として同様のことを試してみましたが、処理時間は伸びました。
* Domaのバージョンも落としてみましたが、同様に処理時間は伸びました。
* Javaを17に上げても、同様に処理時間は伸びました。（体感としては11より遅くなった印象です）

**Comment by nakamura-to** [comment]
最近Eclipseを使っていないので見当違いなことを言っていたらすみません。

> Eclipseから「Project > Clean... > Start a build immediately」を行う。

この時はEclipse内のコンパイラを使ってビルドが行われGradleは使われない認識です。少なくともEclpse 2020-03くらいまではそのような挙動でした。しかし、Eclipse 2023-09ではEclpseからGradleが呼ばれビルドされるということでしょうか？

> このため、Eclipseの問題である気はしています。

私もそんな気がします。
Eclipseに十分なメモリを割り当てたら問題は改善されないでしょうか？

**Comment by inoue-koki** [comment]
回答ありがとうございます！

> この時はEclipse内のコンパイラを使ってビルドが行われGradleは使われない認識です。少なくともEclpse 2020-03くらいまではそのような挙動でした。しかし、Eclipse 2023-09ではEclpseからGradleが呼ばれビルドされるということでしょうか？

いえ、最近のEclipseでもビルドの仕組みは変わっていないと思います。
「Project > Clean... > Start a build immediately」の手順は、単純に「クリーンビルドをしている＝一番時間がかかる時」を言いたかったまでです。

> Eclipseに十分なメモリを割り当てたら問題は改善されないでしょうか？

現在は、`-Xmx4g`を指定しています。
8GBまで増やしてみたんですが、状況変わらずでした。

**Comment by nakamura-to** [comment]
> いえ、最近のEclipseでもビルドの仕組みは変わっていないと思います。
「Project > Clean... > Start a build immediately」の手順は、単純に「クリーンビルドをしている＝一番時間がかかる時」を言いたかったまでです。

なるほど。だとすると、再現手順に記載いただいた「build.gradle の sourceCompatibility targetCompatibility を変更する。」との関係はどうなりますか？「Project > Clean... > Start a build immediately」は、build.gradleの設定を見て動作しているのかしていないかどちらですか？

現象が再現する環境を共有してもらうことは可能でしょうか？Eclipseの設定ファイルが含まれた状態でいただきたいです。

**Comment by inoue-koki** [comment]
> なるほど。だとすると、再現手順に記載いただいた「build.gradle の sourceCompatibility targetCompatibility を変更する。」との関係はどうなりますか？「Project > Clean... > Start a build immediately」は、build.gradleの設定を見て動作しているのかしていないかどちらですか？

分かりづらくて申し訳ないです。

1. build.gradleを変更し、
2. **「Gradle > Refresh Gradle Project」でBuildshipを動かし、変更内容をEclipseの設定ファイルに反映し、**
3. Eclipseからクリーンビルドを行う。

という手順ですので、build.gradleの設定は間接的に見ている認識です。

> 現象が再現する環境を共有してもらうことは可能でしょうか？Eclipseの設定ファイルが含まれた状態でいただきたいです。

計測に使ったDAOが外に出せないものを使っているので、すぐには共有できないですが少し検討させてください。

いったん、Eclipseの設定ファイルだけ貼らせてください。（ほぼデフォルト設定のはずです）
また、build.gradleも貼らせていただきます。余計な依存関係が一部含まれてしまっていますが、ご容赦ください。

* `.classpath`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="src/main/resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/test" path="src/test/java">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path=".apt_generated"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="src" output="bin/test" path=".apt_generated_tests">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
```
* `.factorypath`
```xml
<factorypath>
  <factorypathentry kind='EXTJAR' id='/Users/kinoue/.gradle/caches/modules-2/files-2.1/org.seasar.doma/doma-processor/2.54.2/b95d49ba0cc1d0806d859adaed5cff2bd174cfd/doma-processor-2.54.2.jar' enabled='true' runInBatchMode='false' />
  <factorypathentry kind='EXTJAR' id='/Users/kinoue/.gradle/caches/modules-2/files-2.1/org.seasar.doma/doma-core/2.54.2/b9e06221ca2d0786cc4a08ee858b8250b4a5ad29/doma-core-2.54.2.jar' enabled='true' runInBatchMode='false' />
</factorypath>
```
* `.project`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>all-tables</name>
	<comment>Project all-tables created by Buildship.</comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.buildship.core.gradleprojectbuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.springframework.ide.eclipse.boot.validation.springbootbuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>org.eclipse.buildship.core.gradleprojectnature</nature>
	</natures>
</projectDescription>
```
* `.settings/org.eclipse.buildship.core.prefs`
```ini
arguments=
auto.sync=false
build.scans.enabled=false
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=
eclipse.preferences.version=1
gradle.user.home=
java.home=
jvm.arguments=
offline.mode=false
override.workspace.settings=true
show.console.view=false
show.executions.view=false
```
* `.settings/org.eclipse.jdt.apt.core.prefs`
```ini
eclipse.preferences.version=1
org.eclipse.jdt.apt.aptEnabled=true
org.eclipse.jdt.apt.genSrcDir=.apt_generated
org.eclipse.jdt.apt.genTestSrcDir=.apt_generated_tests
org.eclipse.jdt.apt.reconcileEnabled=true
```
* `.settings/org.eclipse.jdt.core.prefs`
```ini
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
org.eclipse.jdt.core.compiler.codegen.methodParameters=do not generate
org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
org.eclipse.jdt.core.compiler.codegen.unusedLocal=preserve
org.eclipse.jdt.core.compiler.compliance=11
org.eclipse.jdt.core.compiler.debug.lineNumber=generate
org.eclipse.jdt.core.compiler.debug.localVariable=generate
org.eclipse.jdt.core.compiler.debug.sourceFile=generate
org.eclipse.jdt.core.compiler.problem.assertIdentifier=error
org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=disabled
org.eclipse.jdt.core.compiler.problem.enumIdentifier=error
org.eclipse.jdt.core.compiler.problem.reportPreviewFeatures=warning
org.eclipse.jdt.core.compiler.processAnnotations=enabled
org.eclipse.jdt.core.compiler.release=disabled
org.eclipse.jdt.core.compiler.source=11
```
* `.settings/org.springframework.ide.eclipse.prefs`
```ini
boot.validation.initialized=true
eclipse.preferences.version=1
```
* `build.gradle` 
```groovy
def jdkVersion = 11
def domaVersion = '2.54.2'
def lombokVersion = '1.18.30'
def springBootVersion = '2.7.18'

repositories {
    mavenCentral()
}

apply plugin: 'java'

sourceCompatibility = targetCompatibility = jdkVersion

dependencies {
    implementation "org.seasar.doma:doma-core:${domaVersion}"
    annotationProcessor "org.seasar.doma:doma-processor:${domaVersion}"
    runtimeOnly 'com.mysql:mysql-connector-j:8.2.0'

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    implementation 'com.google.code.gson:gson:2.10.1'

    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-validation:${springBootVersion}"
}


apply plugin: 'eclipse'
eclipse {
    classpath {
        file.whenMerged {
            entries << new org.gradle.plugins.ide.eclipse.model.SourceFolder(".apt_generated", "bin/main")
        }
    }
}
eclipseJdt {
    task doLast {
        file('.factorypath').withWriter { writer ->
            def domaCoreJar = configurations.annotationProcessor.copy().find { it.name.startsWith('doma-core-2') }
            def domaProcessorJar = configurations.annotationProcessor.copy().find { it.name.startsWith('doma-processor-2') }

            new groovy.xml.MarkupBuilder(writer).factorypath() {
                factorypathentry(kind:'EXTJAR', id:domaProcessorJar, enabled:true, runInBatchMode:false)
                factorypathentry(kind:'EXTJAR', id:domaCoreJar, enabled:true, runInBatchMode:false)
            }
        }
    }
}


def domaResources = ['doma.compile.config', 'META-INF/**/*.sql', 'META-INF/**/*.script']
task copyDomaResources(type: Copy) {
    from sourceSets.main.resources.srcDirs
    into compileJava.destinationDir
    include domaResources
}
compileJava.dependsOn copyDomaResources
processResources.exclude domaResources
```

**Comment by nakamura-to** [comment]
改善策と言えるかはわかりませんが、Eclipseの開発者に尋ねてみるのが良いと思います。

質問なのですが、パフォーマンスの問題はDomaのAnnotation Processorだけで顕在化していますか？Lombokをお使いのようですがLombokのAnnotation Processorでは問題になりませんか？

**Comment by inoue-koki** [comment]
やはりこれ以上は本家に聞いてみるしかないですよね。。
少しハードルが高めなので、教えていただいた緩和策で様子を見つつ、どうしても待てないなら考えてみたいと思います。
提示いただいたワークアラウンドも、ソース量を考えると少し難しいですが、選択肢として頭に入れておきます。

> 質問なのですが、パフォーマンスの問題はDomaのAnnotation Processorだけで顕在化していますか？Lombokをお使いのようですがLombokのAnnotation Processorでは問題になりませんか？

試していなかったので、lombokのアノテーションを消し依存もなくしてEclipseからクリーンビルドを行ってみました。
結果、ビルド時間は変わらなかったので、lombokでは問題になっていないと言えそうです。

**Comment by nakamura-to** [comment]
lombokでは問題になっていないのですね。ご回答ありがとうございます。

**Comment by nakamura-to** [comment]
#1034 の修正でこの問題はほとんど解消されると思います。
リリースされたらお試しください。
もし問題が解決されないようであればこのissueを再度オープンにしたいと思います。

**Comment by nakamura-to** [comment]
v2.55.0としてリリース済みです。
https://github.com/domaframework/doma/releases/tag/2.55.0

**Comment by inoue-koki** [comment]
対応ありがとうございます！こちらでも確認しました。

きちんと計測していませんが、Java8の時と比較するとまだ少し遅く感じるものの、対応前と比較すると明らかにビルド時間が短くなっていることが確認できました。
