### ISSUE TITLE
SelectOptionsでソートしたい

### ISSUE THREAD

**Issue by kurages** [domaframework/doma#1028]
**Description**
ページング処理だけでなくソートもjavaでしたい要望になります。
現在は埋め込み変数コメントで対応していますが、
ただでさえ複雑になりがちな検索SQLに画面側の要件を流出させたくない為です。

**Implementation ideas**
このような使い方を想像しています。

```
Employee_ e = new Employee_();
SelectOptions selectOptions = SelectOptions.get().sort(e.id, e.val);
List<Employee> all = dao.selectAll(selectOptions);
```

Criteria APIが混ざらないほうが良いと思うのでEntityからカラムのEnumをAPTで作成して指定できるのがベストでしょうか。

もし対応しない・できない理由がなく取り込んで頂けるようであれば、もう少し詰めて自分の方で実装してみます。(まだ変更場所の見当はついていないですが)

追記
- asc/desc, nulls first/lastをどう表すか
- 関数を通していたりselect句でASしてたりする値の対応

少し実装方法を考えてみましたが、単純な対応では難しそうですね

**Comment by nakamura-to** [comment]
Criteria APIを利用されているのであればDAOやSelectOptionsは使わずにCriteria APIを使って実現しても良いと思いますが、Criteria APIでは生成が難しい複雑なSQLを発行しているということでしょうか？

> もし対応しない・できない理由がなく取り込んで頂けるようであれば

すでに挙げてくださっていますが、実現は簡単ではない気がします。
今は埋め込み変数コメントを使っているとのことですが、埋め込み変数コメントを使い続ける問題点を共有いただけたら何かコメントできるかもしれません。埋め込み変数コメントを使うからと言って必ずしも画面側の要件がSQLに流出するというわけではないように感じます。

**Comment by nakamura-to** [comment]
以下のようなSQLテンプレートで対応するということですね。良いと思います。

```sql
select * from employee where salary = /* salary */100 
/*%if !sortColumns.isEmpty() */
  /*# "order by" */
  /*%for c : sortColumns *//*# c *//*%if c_has_next *//*# ", " *//*%end *//*%end */
/*%end */
```

利用しているデータベースによってはORDER BYのキーワードを動的に出力する形式に対応していないかもしれません。
その場合はデフォルトのソート条件として主キーを指定するのが良いと思います。
（主キーを指定して処理時間が遅くなることは考えにくいと思っています）

**Comment by kurages** [comment]
ありがとうございます。
上記テンプレートで対応できそうなので
こちらの要望は取り下げさせてください。
諸々ありがとうございました。
