### ISSUE TITLE
Prevent prepareIdValue if ignoreGeneratedKeys is true

### ISSUE THREAD

**Issue by uc4w6c** [domaframework/doma#1038]
**Description**
In PostgreSQL, if I execute a batch insert on a table that has a `GENERATED ALWAYS AS IDENTITY` column, an error occur.
Error: `Column "id" is an identity column defined as GENERATED ALWAYS.`

This is because in the case of PostgreSQL batch insert, the sequence is obtained in advance and set to insert.
https://github.com/domaframework/doma/issues/98

**Implementation ideas**
Since the `ignoreGeneratedKeys` option has been added, I would like to avoid retrieving sequences in advance when specifying this option.
https://github.com/domaframework/doma/pull/861

**Comment by nakamura-to** [comment]
Hi.

If you use a customized dialect as follows, you can avoid that error.

```java
public class MyPostgresDialect extends PostgresDialect {

    @Override
    public boolean supportsIdentityReservation() {
        return false;
    }
}
```

This dialect works even when combined with the `ignoreGeneratedKeys` option.

**Comment by uc4w6c** [comment]
Hi. Thank you for developing doma2.

I know that. However, that method does not set the id to the entity.
If I use that method and want to set the id to the returned entity of a batch insert via SQL, the same issue as https://github.com/domaframework/doma/issues/98 will occur.

That's why I wanted to avoid pre-fetching sequences only when ignoreGeneratedKeys is set.
What do you think?

**Comment by nakamura-to** [comment]
Would you like to extract the generated ID from the Entity when you use batch INSERT? In your pull request, the extraction of the generated ID is not possible. Is this intentional? 

I believe that both your pull request and my suggestion to create a custom Dialect will yield the same result.

> What do you think?

Currently, Doma does not support this, but I think the following approach could meet your needs:

- Call `Statement#getGeneratedKeys` after each execution of `Statement#executeBatch` to retrieve the generated IDs.
- Set these generated IDs in the entity.

This functionality is supported in [Komapper](https://github.com/komapper/komapper), the Kotlin OMR I am developing. If you could submit a pull request with such functionality to Doma, I would be glad to incorporate it.

**Comment by uc4w6c** [comment]
I'm sorry. My understanding and explanation were lacking.

Suppose the following two tables exist in the same DB.
  - IDENTITY always
  - IDENTITY by default

> I believe that both your pull request and my suggestion to create a custom Dialect will yield the same result.

For tables with `IDENTITY always`, as you say, my pull request has the same result as setting `supportsIdentityReservation` to `false`.

However, For tables with `IDENTITY by default`, if `supportsIdentityReservation` is `false` and `ignoreGeneratedKeys` is `false`, the sequence is retrieved and set for each insert, so https://github.com/domaframework I think the issue with /doma/issues/98 occurs.

```shell:
insert into IDENTITY_STRATEGY_ANY (value) values (99)
2024-01-10T15:37:26.196+09:00 DEBUG 15452 --- [           main] o.seasar.doma.jdbc.LogKind.SQL.SELECT    : [DOMA2076] SQL LOG : PATH=[null],
select currval(pg_catalog.pg_get_serial_sequence('IDENTITY_STRATEGY_ANY', 'id'))
2024-01-10T15:37:26.197+09:00 DEBUG 15452 --- [           main] org.seasar.doma.jdbc.LogKind.DAO         : [DOMA2221] EXIT   : CLASS=com.example.domabatchinsert.jobs.any.IdentityStrategyAnyDaoImpl, METHOD=batchInsert
```

In the case of my pull request, if `ignoreGeneratedKeys` is `false`, the sequence will be obtained and inserted for the number of inserts first, so there will be no speed degradation.

```shell:
select nextval(pg_catalog.pg_get_serial_sequence('IDENTITY_STRATEGY_ANY', 'id')) from generate_series(1, 100)
…

insert into IDENTITY_STRATEGY_ANY (id, value) values (3999, 998)
2024-01-10T15:39:38.138+09:00 DEBUG 15586 --- [           main] o.s.doma.jdbc.LogKind.SQL.BATCH_INSERT   : [DOMA2076] SQL LOG : PATH=[null],
insert into IDENTITY_STRATEGY_ANY (id, value) values (4000, 999)
2024-01-10T15:39:38.140+09:00 DEBUG 15586 --- [           main] org.seasar.doma.jdbc.LogKind.DAO         : [DOMA2221] EXIT   : CLASS=com.example.domabatchinsert.jobs.any.IdentityStrategyAnyDaoImpl, METHOD=batchInsert
```

This is the code for reference: https://github.com/uc4w6c/doma-batchinsert

However, since it is a PostgreSQL-only function and has limited uses, and I can customize it myself, I would like to leave it up to you to decide whether to support it or not.
