### ISSUE TITLE
DOMA4084 error occurs when including the Embeddable class

### ISSUE THREAD

**Issue by uc4w6c** [domaframework/doma#1046]
Thank you for always developing.

**Describe the bug**
I have the following entity and dao.

```java
@Entity
public record EmployeeEntity(
  @Id long id, Address address){}

@Embeddable
public record Address(
  String city, String street) {}
```

```java
@ConfigAutowireable
@Dao
public interface EmployeeDao {
  @Update(include = "address.city")
  Result<EmployeeEntity> update(EmployeeEntity entities);
}
```

The following error occurs.

`[DOMA4084] The property "address.city" is not found in the entity class ...`

**Expected behavior**
I also want to use include for Embeddable classes.

**Additional context**The target code that I think should be fixed

https://github.com/domaframework/doma/blob/master/doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/entity/EntityPropertyNameCollector.java#L31-L41

But I don't know how to make good code.

Also, doma-core may work without any modification.
The name contained address.city when I debugged.

https://github.com/domaframework/doma/blob/e37714176e816dd1809d592bb5e02820bd741614/doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoBatchModifyQuery.java#L84

**Comment by nakamura-to** [comment]
Thank you for your feedback. I will look into it.

**Comment by uc4w6c** [comment]
@nakamura-to
Thank you for resolving the issue.

**Comment by nakamura-to** [comment]
This fix has been included in the release of Doma 2.55.2. Please feel free to try out the revised version.

**Comment by uc4w6c** [comment]
@nakamura-to 
I created a PR #1049. 
Please leave a review. Please check.

**Comment by nakamura-to** [comment]
Thanks!
