### ISSUE TITLE
InsertしたレコードのEntityが欲しいです

### ISSUE THREAD

**Issue by matsumana** [domaframework/doma#109]
質問です。

具体的に言うと、親子関係があるテーブルの親を先にINSERTしてそのIDを子のINSERTに使うので、INSERTしたレコードのEntityを戻り値として受け取りたいです。

[ドキュメント](http://doma.readthedocs.org/ja/stable/query/insert/#id3)にある`org.seasar.doma.Result`が今使っているバージョン(2.6.0)には含まれていないのですが、2.6.0だとどうすれば良いでしょうか？

それと、戻り値のクラスはイミュータブルなエンティティである必要があるみたいですが、
エンティティクラスはDoma-Genで生成しています。出来れば戻り値にそのエンティティを使いたいです。
良い方法はないでしょうか？

**Comment by backpaper0** [comment]
2.6.0にも`Result`はありますよ？
https://github.com/domaframework/doma/blob/2.6.0/src/main/java/org/seasar/doma/jdbc/Result.java

**Comment by matsumana** [comment]
ドキュメントが`org.seasar.doma.Result`ってなってたので別物かと思ってました。
`org.seasar.doma.jdbc.Result`で良いんですね。ありがとうございます。

**Comment by backpaper0** [comment]
ドキュメント間違いのようですね。修正してプルリクエストしておきます。

**Comment by matsumana** [comment]
ありがとうございます。

**Comment by matsumana** [comment]
エンティティはDoma-Genで生成してるので、以下の様なクラスが出来るのですが、

```java
@Entity(listener = EmployeeListener.class)
@Table(name = "employee")
public class Employee {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	Integer id;

	@Column(name = "name")
	String name;
}
```

InsertしたレコードのEntityを戻り値に使いたい場合、こういうクラスを別に作る必要があると思ってます。

```java
@Entity(immutable = true)
public class ImmutableEmployee {

	final Integer id;
	final String name;

	public ImmutableEmployee(Integer id, String name) {
		this.id = id;
		this.name = name;
	}
```

そして、Daoのメソッドをこういう風に引数と戻り値を一致させる。

```java
@Insert
Result<ImmutableEmployee> insert(ImmutableEmployee employee);
```

せっかくDoma-Genでエンティティを作っているので、イミュータブルなクラスを自分で別途作りたくないと思うのですが、
良い方法はないでしょうか？

イミュータブルなクラスになっている理由も知りたいです。

**Comment by matsumana** [comment]
質問の補足です。

[ドキュメント](http://doma.readthedocs.org/ja/stable/query/insert/#id3)に
`パラメータがイミュータブルなエンティティクラスの場合、 戻り値はそのエンティティクラスを要素とする org.seasar.doma.Result でなければいけません。`

と書いてあるので、ミュータブルなエンティティクラスでもいけそうな印象を受けたのですが、

```java
@Insert
Result<Employee> insert(Employee employee);
```

と書くとコンパイル時に以下のエラーになってしまいます。

`[DOMA4001] 戻り値の型は更新件数を示すintでなければいけません。`

なので、イミュータブルなクラスに限定されていると思った次第です。

**Comment by backpaper0** [comment]
ミュータブルなエンティティの場合、insertしたあとにidに値がセットされます。

つまり、

```java
Employee emp = new Employee();
emp.name = "うらがみ";

assert emp.id == null;

//ここでSQLが発行されたあと、idに採番された値がセットされる
dao.insert(emp);

assert emp.id != null;
```

となります。

ですので、

> 親を先にINSERTしてそのIDを子のINSERTに使う

という要望はミュータブルなエンティティと、戻り値がintのinsertメソッドで叶えられるはずです。
(この要望をすっかり見落としていました。すみません。）

**Comment by matsumana** [comment]
* 引数がミュータブルなエンティティならそのエンティティのidにセットされる
* イミュータブルなエンティティならidがセットされたエンティティが戻り値で返る

って事なんですね。
ミュータブルでも戻り値で返すのかと思い込んでました。

ありがとうございました。

**Comment by matsumana** [comment]
解決しましたのでcloseします。
ありがとうございました。
