### ISSUE TITLE
更新クエリ(include)の説明が誤っている

### ISSUE THREAD

**Issue by mitoma** [domaframework/doma#120]
「@ Update の include 要素に指定されたプロパティのみを**削除対象**とします。」という記述は、**更新対象** の間違いではないでしょうか？
https://github.com/domaframework/doma/blob/master/docs/sources/query/update.rst#include

**Comment by nakamura-to** [comment]
ありがとうございます :smile:

**Comment by mitoma** [comment]
:+1: どもです！
