### ISSUE TITLE
SQLiteDialect#isUniqueConstraintViolated is incorrect

### ISSUE THREAD

**Issue by mintdaniel42** [domaframework/doma#1210]
**Describe the bug**
SQLiteDialect#isUniqueConstraintViolated does not recognize SQLite primary key unique constraint violations

**Expected behavior**
UniqueConstraintException is thrown

**Actual behavior**
SQLExecutionException is thrown

**To Reproduce**
1. Use SQLite
2. Insert an entry with unique key twice
3. Exception not catched

**Fix**
The current way to check is by comparing the message of the exception like below

```
public boolean isUniqueConstraintViolated(SQLException sqlException) {
    if (sqlException == null) {
      throw new DomaNullPointerException("sqlException");
    }
    SQLException cause = getCauseSQLException(sqlException);
    String message = cause.getMessage();
    return message != null
        && message.startsWith("[SQLITE_CONSTRAINT]")
        && message.contains(" unique)");
}
```

But this will never work because the exception looks like this

`[SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: <property>)`

I suggest to change the body of the method to something like this

```
@Override
public boolean isUniqueConstraintViolated(@NonNull final SQLException sqlException) {
	final var cause = getCauseSQLException(sqlException);
	final var message = cause.getMessage();
	return message != null
			&& message.startsWith("[SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed:");
}
```

**Comment by nakamura-to** [comment]
Thank you for your report.
I will look into it.
