### ISSUE TITLE
Kotlinでのエンティティクラスについて

### ISSUE THREAD

**Issue by worifon** [domaframework/doma#148]
Kotlin+domaではエンティティクラスで「継承は使わない」とあります。
created_at, update_at, versionのようなすべてのテーブルに共通的に付加したいフィールドに対して継承を使った経験がありましたが（javaですが）、こういうことはできないということですね？
またエンベッダブルクラスを使うといいかと思いましたが、「楽観的排他制御用のバージョンを定義できません。」とのことなので、これもできないということですね？

**Comment by nakamura-to** [comment]
以下のように継承はできます。

```kt
@Entity(immutable = true)
open class Common(
        @Id
        @GeneratedValue(strategy = org.seasar.doma.GenerationType.IDENTITY)
        val id:Int? = null)

@Entity(immutable = true)
class Person(
        id:Int? = null,
        val name:Name,
        val age:Int?,
        val address: Address) : Common(id)
```

しかし、Data Classが使えない（つまり便利なcopyメソッド使えない）ですし、記述量もそれほど変わらないので多少の重複には目をつぶってフラットに記述するのが良いと考えています。

> またエンベッダブルクラスを使うといいかと思いましたが、「楽観的排他制御用のバージョンを定義できません。」とのことなので、これもできないということですね？

はい、こちらはその通りです。エンベッダブルクラスは再利用性よりも意味のあるデータをグループ化するために利用するのが良いと思います。

**Comment by worifon** [comment]
ご回答、ご教示をありがとうございました。理解しました。
