### ISSUE TITLE
SQLの埋め込み変数コメントの拡張希望

### ISSUE THREAD

**Issue by bakenezumi** [domaframework/doma#149]
いつも利用させてもらっています。
ありがとうございます。

SQLの埋め込み変数コメントの機能につきまして、１点拡張のお願いになります。

```java
String code = "abc";
```
とあったとき、

```sql
select ...
from ...
where code = '/*# code */'
```
とSQLを書くと期待した`where code = 'abc'`ではなく、`where code = '/*# code */'`
と現在の仕様では展開されるようです。

こちらを`where code = 'abc'`になるよう拡張していただくことは可能でしょうか。

といいますのが、codeの値により異なる実行計画が選択されるケースで、プリペアしたくない場合があるからです。
旧S2DAOでは埋め込みコメント`/*$引数名*/`によりステートメントを明示的に分けることで対処しておりました。

インジェクションのリスクがややあがる懸念はあるかと思いますが、禁則文字のチェックは評価後に行われているようなので問題はないのでは、と考えます。

ご検討のほどよろしくお願い致します。

**Comment by nakamura-to** [comment]
`'/*# code */'` のような文字列の中をDomaが自動で書き換えるように変更するのは互換性の面で採用しにくいです。

少し冗長ですが、このように書けるようにするのはどうでしょうか？

```sql
select ...
from ...
where code = /*# @raw("'" + code + "'") */
```

`@raw()` で返された値に対しては禁則文字のチェックを行わないようにします。
したがって、最終的なSQLは次のようにできます。

```sql
select ...
from ...
where code = 'abc'
```

**Comment by bakenezumi** [comment]
回答ありがとうございます。

要求としては満たせますのでご提示の実装で問題ないです。
ただ、変数の中身に対しては事前に禁則チェックを行う必要がでてくるため、

```sql
select ...
from ...
where code = /*# @literal(code) */
```
のように特化した関数もあるとありがたいです。

```java
public String literal(String text) {
  // 禁則文字のチェック
  if (...) throw new JdbcException(...)
  return "'" + text + "'";
}

// IN用 
public String literal(Iterable<String> texts) {
  // 禁則文字のチェック
  ...
  return "('" + String.join("','", texts) + "')";  
}

```

**Comment by nakamura-to** [comment]
変数の中身には禁則チェックかけたいのですね。確かにその方が安全で良いと思います。
ということであれば、新しく専用のSQLコメントを用意してしまった方がスッキリするかもしれません。

```sql
select ...
from ...
where code = /*^ code */'test'
```

こうするのはどうでしょうか？

- codeが数値ならそのまま、数値以外なら`toString()`してシングルクォートで囲んで出力
- Iterableならカンマで連結
- バインド変数コメントに合わせてテスト用データは必須
- この新しいコメントの名称は「リテラル変数コメント」
- 埋め込み変数コメントは主にテーブル名やorder byを埋め込む場合に使ってもらうことにしてリテラル変数コメントとは使い分ける

**Comment by bakenezumi** [comment]
全く問題ありません。

丁寧な考慮ありがとうございます。

**Comment by nakamura-to** [comment]
では、この方向で機能追加しようと思います。

**Comment by bakenezumi** [comment]
大変助かります。よろしくお願い致します。
