### ISSUE TITLE
SelectBuilder で ' の中に param を設定するとパラメータが設定されない

### ISSUE THREAD

**Issue by k--kato** [domaframework/doma#152]
* Doma Version: 2.10.0
* OS Version: Windows 10 Pro x64
* Database: PostgreSQL 9.5 x64

SelectBuilder で `'` の中に param を設定すると，パラメータが設定されません。

#### コード
```java
SelectBuilder sb = SelectBuilder.newInstance(config);
sb.sql("select '").param(String.class, "bar");
sb.sql("'");
System.out.println(sb.getSql().getFormattedSql());
```

#### 実行結果
```bash
select '/*p1*/0
'
```

#### 期待する結果
```bash
select 'bar'
または
select '''bar'''
```

param の用途が不適切と思われますが，ご確認をよろしくお願いします。
※SQL Injection のサニタイジングを期待して使用しています

**Comment by k--kato** [comment]
解決しました。

```java
SelectBuilder sb = SelectBuilder.newInstance(config);
sb.sql("select ''||").param(String.class, "bar");
sb.sql("||''");
System.out.println(sb.getSql().getFormattedSql());
```

お騒がせしました。

**Comment by nakamura-to** [comment]
リテラルを埋め込みたいということでしょうか。
次のように書けるようにすることを検討しています。

```java
SelectBuilder sb = SelectBuilder.newInstance(config);
sb.sql("select ").literal(String.class, "bar");
```

**Comment by k--kato** [comment]
@nakamura-to 
はい，サニタイジングされたリテラルが理想です。`.literal` があれば非常に助かります。

**Comment by nakamura-to** [comment]
サニタイジング（SQLエスケープ）はDomaでは行わず、 `PreparedStatement` に任せる方針です。

今回のようにリテラルで埋め込む場合には、あらかじめ定義された安全な値のみを使うのが良いと思います。そうすればそもそもエスケープの必要がありません。
どうしても外部から受け取る信頼できない値を使いたいのであればリテラルを埋め込むのではなく、やはりバインド変数（ 上記の例で言うと`param()`）を使ったほうが安全です。

上述の`literal()`を使った場合は、文字列にシングルクォートが含まれかどうかをチェックし、含まれる場合には例外をスローするつもりです。

**Comment by k--kato** [comment]
@nakamura-to 
把握しました。`param`  と `literal` と使い分けに気をつけたいと思います。
`literal` に ```` が含まれると例外をスローするのはとても良いと思います。
