### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by syuhaitao** [domaframework/doma#164]
How to use the same set of Entity, how to meet the MySQL and Oracle's primary key generation strategy

**Comment by nakamura-to** [comment]
> How to use the same set of Entity

Entity classes are not bound to a specific data source.
You can change data sources with Config class.

> how to meet the MySQL and Oracle's primary key generation strategy

Use the `GenerationType.TABLE` strategy.

## Sample Code
### Entity

```java
@Entity
public class Person {
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    @TableGenerator(pkColumnValue = "TABLE_STRATEGY_ID", allocationSize = 50)
    public Integer id;
    public String name;
}
```

### DDL for `GenerationType.TABLE` strategy.

```sql
CREATE TABLE TABLE_STRATEGY(ID NUMERIC(8) NOT NULL PRIMARY KEY, VALUE VARCHAR2(10));
```

### DAO

```java
@Dao
public interface PersonDao {
    @Insert
    int insert(Person person);
}
```

### Config for Oracle

```java
public class OracleConfig implements Config {
    private static Dialect dialect = new OracleDialect();

    public Dialect getDialect() {
        return dialect;
    }

    public DataSource getDataSource() {
        return ...
    }
}
```

### Config for Mysql

```java
public class MysqlConfig implements Config {
    private static Dialect dialect = new MysqlDialect();

    public Dialect getDialect() {
        return dialect;
    }

    public DataSource getDataSource() {
        return ...
    }
}
```

### Client

```java
Person person = new Person();
person.name = "Jhon";
PersonDao dao = new PersonDaoImpl(new OracleConfig()); 
// PersonDao dao = new PersonDaoImpl(new MysqlConfig());
dao.insert(person);
```

**Comment by syuhaitao** [comment]
Issue is solved,but Generationtype.table concurrent problem how to solve?

**Comment by nakamura-to** [comment]
Can you tell me what kind of concurrent problem you have? 
Are primary key values duplicated?

**Comment by syuhaitao** [comment]
primary key values duplicated, and This ID generation strategy will not be efficient in the case of high concurrency?

**Comment by nakamura-to** [comment]
> primary key values duplicated

Does it really occur in your environment? Or is it just your question?

> This ID generation strategy will not be efficient in the case of high concurrency?

No, it will not be efficient.But there are two things to improve performance.

### Point 1: Assign larger value to the `allocationSize` 

It reduces the frequency of DB access. 

```java
@TableGenerator(pkColumnValue = "TABLE_STRATEGY_ID", allocationSize = 100)
public Integer id;
```
### Point 2: Make transaction short for ID generation

You can use `org.seasar.doma.jdbc.RequiresNewController`. This is also useful to prevent primary key values duplication.

Following code is a sample implementation that uses SpringFramework.

```java
import org.seasar.doma.jdbc.RequiresNewController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.support.DefaultTransactionDefinition;

public class SpringRequiresNewController implements RequiresNewController {

    private final PlatformTransactionManager txManager;

    @Autowired
    public SpringRequiresNewController(PlatformTransactionManager txManager) {
        this.txManager = txManager;
    }

    @Override
    public <R> R requiresNew(Callback<R> callback) throws Throwable {
        DefaultTransactionDefinition def = new DefaultTransactionDefinition();
        def.setName("SomeTxName");
        def.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
        TransactionStatus status = txManager.getTransaction(def);
        R result;
        try {
            result = callback.execute();
        } catch (Exception ex) {
            txManager.rollback(status);
            throw ex;
        }
        txManager.commit(status);
        return result;
    }
}
```

An instance of `RequiresNewController` must be return from `org.seasar.doma.jdbc.Config#getRequiresNewController()`.

**Comment by syuhaitao** [comment]
THANK YOU !  This problem does not appear in the project, which is a question I think of

**Comment by syuhaitao** [comment]
GenerationType.TABLE is not without the high efficiency of GenerationType.IDENTITY and GenerationType.SEQUENCE?

**Comment by syuhaitao** [comment]
If you want Mysql to use GenerationType.IDENTITY and Oracle to use GenerationType.SEQUENCE, how to achieve? EntityListener?

**Comment by nakamura-to** [comment]
GenerationType.TABLE is not so bad. It may be acceptable for you.

> If you want Mysql to use GenerationType.IDENTITY and Oracle to use GenerationType.SEQUENCE, how to achieve? EntityListener?

There is no good way to achieve it.

Can you tell me which version of Oracle Database you use?
I have a plan to support GenerationType.IDENTITY for Oracle Database 12c. If you use Oracle Database 12c, you can use only GenerationType.IDENTITY  for both Mysql and Oracle.
