### ISSUE TITLE
水平分割したテーブルの利用方法

### ISSUE THREAD

**Issue by satoyama-m** [domaframework/doma#168]
水平分割したテーブルの利用方法

Doma では、データ分散のためにテーブルを水平分割するにはどのような Dao を作ればよいでしょうか。

例えば、1 つのテーブルを同じスキーマのまま books_p1, books_p2, ... books_pX と作っていき、
時間や名前などの一定条件でレコードをいれておくテーブルを決めるものとします。
Dao のメソッドから以下のクエリで分割されたテーブルの番号を指定してアクセスしてみました。

    SELECT * FROM books_p/* tableNo */0 WHERE id = /* id */0

ただ、テーブル名に対してパラメーターを埋め込むことはできないようで、以下のようなエラーとなりました。

    org.seasar.doma.jdbc.SqlExecutionException: [DOMA2009] SQLの実行に失敗しました。
    SQLファイルパス=[META-INF/net/satoyamam/BooksDao/selectById.sql]。
    ログ用SQL=[SELECT * FROM books_p1 WHERE id = 1]。
    原因は次のものです。com.microsoft.sqlserver.jdbc.SQLServerException: オブジェクト名 &#39;books_p@P0&#39; が無効です。。
    根本原因は次のものです。com.microsoft.sqlserver.jdbc.SQLServerException: オブジェクト名 &#39;books_p@P0&#39; が無効です。
    	at org.seasar.doma.jdbc.command.SelectCommand.execute(SelectCommand.java:74)
    	at net.satoyamam.BooksDaoImpl.selectById(BooksDaoImpl.java:44)
    	at net.satoyamam.BookController.index(BookController.java:23)
    ...

Dao からアクセスするテーブル名を Dao のメソッド引数から動的に変更する場合、
ドキュメントに書かれているような CommandImplementors や QueryImplementors を独自に拡張していくしかないのでしょうか。

また、水平分割されたテーブルを Doma から扱うにあたって、より良い方法はありますでしょうか。

お手すきにて、助言をいただけますと幸いです。

**Comment by nakamura-to** [comment]
テーブル名を動的に変化させたい場合は[埋め込み変数コメント](http://doma.readthedocs.io/ja/2.12.1/sql/#id13)を使ってください。
```sql
SELECT * FROM books_p/*# tableNo */ WHERE id = /* id */0
```

CommandImplementors や QueryImplementorsはよほどのことがない限り使う必要は出てこないと思います。

**Comment by satoyama-m** [comment]
埋め込み変数コメントで無事アクセスすることができました。
ご教示いただきありがとうございました。
