### ISSUE TITLE
Daoインターフェイスの型パラメータ定義に関しての質問

### ISSUE THREAD

**Issue by disc99** [domaframework/doma#185]
## 概要
現在Daoインターフェイスに型パラメータを定義した場合、下記のようなアサートが行われていると思います。

```
[DOMA4059] Daoインタフェースには型パラメータを定義できません。 at com.example.BaseDao
```

ソースを読み切れていないので質問になってしまうのですが、こちらのアサートはDaoの実装を生成する上では止む終えない処理になるのでしょうか？
また、こちらの回避する方法はないでしょうか？

## 背景
現在、Domaを使用させてもらう上で汎用的なDaoインターフェイスの定義をできないか検討しています。
その中で、デフォルトメソッドと併用することで以下のような処理を考えていました。

```java
// 汎用的なDaoインターフェイス
@Dao
interface BaseDao {
    default <T> List<T> findAll(Class<T> clazz) {
        Config config = Config.get(this);
        SelectBuilder builder = SelectBuilder.newInstance(config);
        EntityType<T> entityType = EntityTypeFactory.getEntityType(clazz, config.getClassHelper());
        builder.sql("SELECT * FROM " + entityType.getTableName());
        return builder.getEntityResultList(clazz);
    }
}

// エンティティ単位のインターフェイス
@Dao
interface MessageDao extends BaseDao {}

// 使用
class Main {
    void sample() {
        MessageDao dao = ...; // 何かしらの方法で初期化
        List<Message> messages = dao.selectAll(Message.class);
    }
}
// * サンプルコードのため詳細な定義やバリデーションなどは省略
```

こちらのアプローチで実現は出来そうなのですが、この方法だと必ず引数にClassやインスタンスを渡さなければならないため、もう少しシグネチャを整理できないかと考えていました。

具体的にはこちらで紹介されている型パラメータの定義によるアプローチを利用できればと考えています。
http://d.hatena.ne.jp/Nagise/20131121/1385046248 *1

```java
// 型パラメータ定義を追加
@Dao
interface BaseDao<T> {    
    // 引数のClassとメソッドに対する型パラメータ定義が省略可能
    default List<T> findAll() {
        Class<T> clazz = ..; // *1 の方法で型パラメータからClassを生成

        // 以下の処理は変更前と同様
        Config config = Config.get(this);
        SelectBuilder builder = SelectBuilder.newInstance(config);
        EntityType<T> entityType = EntityTypeFactory.getEntityType(clazz, config.getClassHelper());
        builder.sql("SELECT * FROM " + entityType.getTableName());
        return builder.getEntityResultList(clazz);
    }
}

// interfaceの継承時にEntityとなるクラスの指定
@Dao
interface MessageDao extends BaseDao<Message> {}

// 使用
class Main {
    void sample() {
        MessageDao dao = ...;
        List<Message> messages = dao.selectAll();  // 引数が不要になる
    }
}
```

これが可能になれば、ユースケースに合わせ汎用インターフェイスの拡張もしやすそうな気がします。

```java
// 全Dao共通のDao
@Dao
interface BaseDao<T> {
    default <T> List<T> findAll() {
        // ...
    }
    default int count() {
        // ...
    }
}
// 単一主キー用Dao
@Dao
interface SingleIdDao<T, ID> extends BaseDao {
    default List<T> findById(ID id) {
        // ...
    }
}
//　複合主キー用Dao
@Dao
interface TwinIdDao<T, ID1, ID2> extends BaseDao {
    default List<T> findById(ID1 id1, ID2 id2) {
        // ...
    }
}
```

Domaの設計思想として、SELECT系のSQL構築は行わないというのがあるのは承知しており、私もその思想には賛同しております。

しかし、潜在的なニーズとして基本となるSQLを構築して欲しいというケースもあるように思い、ユーザが許容する範囲内で自前でJavaコードによる汎用SQL生成の手段として使用できないかと質問させてもらいました。

お手すきのときに、確認して頂けましたら幸いです。

**Comment by nakamura-to** [comment]
このような仕様になっている理由は、 `@Select` や `@Insert` が注釈されたメソッドに型パラメータが存在すると注釈処理時に適切なコードを生成できないからです。
例えば、次のようなコードを考えてみます。

```java
@Dao
interface GenericDao<T> {
  @Select
  List<T> select();
}
```

Doma は注釈処理時に戻り値の `List` の要素の型がエンティティクラスなのか基本型（Integerなど）なのかを見て生成するコードを変えているのですが、型パラメータを指定されると区別できないためコード生成できません。

一方でメソッドがデフォルトメソッドの場合はどうかというと、コードを生成する必要がないので型パラメータがあっても特に困りません。したがって、もし対応するとしたら、デフォルトメソッドのみが定義された Dao インタフェースであれば型パラメータの利用を認めるというように制限を緩和してもいいかもしれません。

> また、こちらの回避する方法はないでしょうか？

注釈処理に手を入れない限りは、回避はできないと思います。

**Comment by nakamura-to** [comment]
#188 でデフォルトメソッドのみを持つインタフェースを継承できるようにしてみました。こんな感じで使えます。

```java
// @Dao は注釈しない
interface BaseDao<T> {    
    default List<T> findAll() {
        ...
    }
}
```

```java
// @Dao は注釈しない
interface SingleIdDao<T, ID> extends BaseDao {
    default List<T> findById(ID id) {
        // ...
    }
}
```

```java
// デフォルトメソッドのみを持つインタフェースを複数継承できる。
// 親インタフェースの型パラメータの数に制限はない。
@Dao
interface MessageDao extends BaseDao<Message>, SingleIdDao<Message, Integer> {
}
```

なお、 `@Dao` が注釈されたインタフェースに型パラメータを宣言できない仕様はこれまで通りですので上記の例では親インタフェースに `@Dao` をつけていません。

**Comment by disc99** [comment]
ご回答ありがとうございます！
あっという間に対応案まで出して頂いて、非常にありがたいです！

> デフォルトメソッドのみを持つインタフェースを複数継承できる。
> 親インタフェースの型パラメータの数に制限はない。

このアプローチであれば、DaoImplでdefaultメソッドによるMixinができるので、当初私が想定していた方法よりも更に汎用性が高そうですね！

**Comment by nakamura-to** [comment]
マージしました。次のバージョンに含めます。
