### ISSUE TITLE
【質問】doma2 クエリビルダーのIn句のパラメータ(List)指定方法

### ISSUE THREAD

**Issue by hinoko58** [domaframework/doma#193]
[doma2クエリビルダーのIn句](https://teratail.com/questions/70746#reply-111833)

上記のリンクと全く同じ質問です。

Domaの動的SQLを作成するため、SelectBuilderを使い、SQLを作成しました。 
ただし、In句にリストの指定方法がわかりません。

試した、ソースは以下になります。

SelectBuilder builder = SelectBuilder.newInstance(config);
builder.sql("select * from user where id in (").param(List.class,Arrays.asList(1,2,3)).sql(")");
builder.getEntityResultList(User.class);

を実行すると、以下のエラーが発生します。

Caused by: org.seasar.doma.internal.jdbc.scalar.ScalarException: [DOMA1007] 型[java.util.List]の値[[1, 2, 3]]に対応するラッパークラスが見つかりません。

domaのバージョンは2.13.0になります。

パラメータにリスト形(もしくは配列)を指定する方法を教えてください。 
よろしくお願いします。

**Comment by nakamura-to** [comment]
リンク先のKiyoshiMotokiさんの回答がベストだと思います。
パラメータにリスト形(もしくは配列)を指定する方法はサポートされていません。
自前でin句を組み立てる必要があります。


今はサポートしていませんが、次のようなメソッドをSelectBuilderに生やしてサポートしてもいいかもしれません。
```java
params(Class<E> elementClass,List<P> params);
```
こんな感じで使う想定です。
```java
SelectBuilder builder = SelectBuilder.newInstance(config);
builder.sql("select * from user where id in (").params(Integer.class,Arrays.asList(1,2,3)).sql(")");
```

**Comment by hinoko58** [comment]
回答ありがとうございます。
サポート指定ない点、了解しました。
`
params(Class<E> elementClass,List<P> params);
`
のサポートしていただければ、幸いです。

よろしくお願いします。

**Comment by nakamura-to** [comment]
#194 で対応しました。

**Comment by hinoko58** [comment]
有難うございます。
