### ISSUE TITLE
Doma2 document Chinese Version

### ISSUE THREAD

**Issue by smallclover** [domaframework/doma#218]
すみませんですが、このDoma2のドキュメントの中国語のバージョン作りたいですが、いかがでしょうか。
このフレームワーク興味がありますので、やりたいんです。

**Comment by smallclover** [comment]
今の計画は全部のドキュメント中国語になります。でも、今は翻訳者は私だけです、翻訳の進捗はおそくなるかもしれませんが、やります！全部終わった後、他のイベントを考えます。

今、このフレームワークは自分のGitにForkしました。翻訳のドキュメントの日本語のバージョン同じようにDocsに放置しました。名前は「xxxxx-zh.rst」になりました。

このドキュメントの意味確実に他の人に伝えます！これは今の目標です。

以上です、ありがとうございます。

**Comment by nakamura-to** [comment]
なるほど！了解しました。
ぜひそのまま進めてください。

Read the Docsへの反映のさせ方については私の方でも考えてみたいと思います。

**Comment by smallclover** [comment]
ありがとうございます、了解しました。

**Comment by nakamura-to** [comment]
We use Crowdin for document localization. Currently, we only have a project translating from English to Japanese. However, if there is still a need for Chinese translation, we will consider creating a project to translate from English to Chinese.

See the Crowdin [doma-docs](https://crowdin.com/project/doma-docs) project.
