### ISSUE TITLE
SQLテンプレートを使ったSQLの組み立てでシングルクォーテーションを使いたい。

### ISSUE THREAD

**Issue by hinoko58** [domaframework/doma#226]
個人的にJAVA側で一番いいORMだと思っています。
SQLを組み立てる際に、/*# xx */の中にシングルクォーテーションがあったらいけないらしく、
以下のエラーが発生します。※SQLインジェクション対応だとは思いますが
回避する方法はあるんでしょうか？
```
[DOMA2116] SQLの組み立てに失敗しました。（[3]行目[6]番目の文字付近）。埋め込み変数コメント[/*#where*/]にシングルクォテーションが含まれています。
```

やりたいこと。

Whereクラスがあってその中身のJson表現
```
{
  "conditions": [
    {
      "field": "id",
      "compare": "=",
      "value": 1,
      "cond": "and"
    },
    {
      "field": "age",
      "compare": ">",
      "value": 10,
      "cond": "and"
    },
    {
      "field": "name",
      "compare": "like",
      "value": "yama",
      "cond": "and"
    }
  ],
  "orderBy": [
    {
      "field": "id",
      "sorting": "desc"
    },
    {
      "field": "age",
      "sorting": "asc"
    }
  ]
}
```

userDao.java
```
@Select
User selectByUsers(Where where);
```

selectByUsers.sql
```

select * from user
where delete_flg = 0
/*# @resoveWhere(whereOrder) */    <- resoveWhereは自作
↑/*#じゃなくてもいい
``` 

の場合、以下のSQLが実行されるようにしたいと思います。
下記の２行目以降を自動で組み立てたいと思います。
なるべくなら、クエリビルダーを使わない方法でやりたいと思います
```
select * from user where delete_flg = 0 
and id = 1 and age > 10 and name like '%yama%' 
order by id desc , age asc
```

なにかヒントなど有りましたら、よろしくおねがいします。

**Comment by nakamura-to** [comment]
シングルクォテーションを認めていないのは、SQLインジェクションを防ぐためです。
望んでいない解決策だということはわかっていますが、やりたいことを見る限りはクエリビルダーが適しているように見えました。

もしくは、どうしてもSQLテンプレートを活かしたいということであれば、[SQLプロセッサ](http://doma.readthedocs.io/ja/stable/query/sql-processor/)を使う方法があります。SQLプロセッサを使うと、SQLテンプレートで組み立てたSQLをJavaコードでさらにカスタマイズできます。
いただいた例で言うと、selectByUsers.sqlに記述されたSQLを取得し、resoveWhereに相当する部分をJavaコードで処理して連結するということができます。

**Comment by hinoko58** [comment]
ご回答ありがとうございます。

SQLプロセッサでSQL取得し、対応することが出来ました。

ありがとう御座います。
