### ISSUE TITLE
日本語テーブル・カラム名で正しく動きません

### ISSUE THREAD

**Issue by yu-aoyama** [domaframework/doma#228]
いつもDoma2を利用させて頂いています。
現在、日本語テーブル・カラム名をDoma2で利用できるのか調査をしています。

以下のEntityクラスを準備してSELECT処理を発行したところ、SELECT結果をEntityに紐付けるタイミングでエラーが発生します。

```

@Entity
@Table(name = "テスト", quote = true)
public class Test extends AbstractEntity {
	@Id
	@Column(name = "テスト項目", quote = true)
	String testColumn;

	public String getTestColumn() {
		return testColumn;
	}

	public void setTestColumn(String testColumn) {
		this.testColumn = testColumn;
	}
}

```

エラー内容
`> org.seasar.doma.jdbc.UnknownColumnException: [DOMA2002] カラム[テスト項目]が結果セットに含まれますが、このカラムにマッピングされたプロパティがエンティティクラス[Test]に見つかりません。次の3つの内のいずれかの対応が必要です。1)エンティティクラスに[テスト項目]という名前のプロパティを定義する。2)任意の名前のプロパティに@Columnを注釈し@Columnのname要素に[テスト項目]を指定する。3)UnknownColumnHandlerに未知のカラムを無視するような実装をしorg.seasar.doma.jdbc.Configに設定する。`

原因を色々調べてみますとAPTで自動生成された「_Test.java」の中で文字化けが起きていることが分かりました。

```
@javax.annotation.Generated(value = { "Doma", "2.19.2" }, date = "2018-04-15T00:57:03.061+0900")
public final class _Test extends org.seasar.doma.jdbc.entity.AbstractEntityType<Test> {

  …

    /** the testColumn */
    public final org.seasar.doma.jdbc.entity.AssignedIdPropertyType<java.lang.Object, Test, java.lang.String, Object> $testColumn = new org.seasar.doma.jdbc.entity.AssignedIdPropertyType<>(Test.class, java.lang.String.class, java.lang.String.class, () -> new org.seasar.doma.wrapper.StringWrapper(), null, null, "testColumn", "�e�X�g����", __namingType, true);

  …

    private _Test() {
        __listenerSupplier = () -> ListenerHolder.listener;
        __immutable = false;
        __name = "Test";
        __catalogName = "";
        __schemaName = "";
        __tableName = "�e�X�g";
  …

```

上記「_Test.java」の文字化け部分を手動で修正してみたところ正しく動く事が確認できたので、APTの処理だけ問題ありそうです。

そもそも日本語テーブル・カラム名は明示的なサポート対象ではないようには思うのですが
上記何らかの方法で回避することは可能でしょうか？

当方の実行環境は、
Doma 2.19.2
Windows
Eclipse Neon(4.6.3)
jdk-8u131-windows-x64
となっています。

**Comment by nakamura-to** [comment]
.javaファイルのエンコーディングの問題だと思います。
Eclipseの設定でエンコーディングをUTF-8に設定して試してみてもらえないでしょうか？

日本語テーブル・カラムですが、エンコーディングがUTF-8であることを前提にサポートしています。

**Comment by yu-aoyama** [comment]
迅速な回答ありがとうございます。

 > 日本語テーブル・カラムですが、エンコーディングがUTF-8であることを前提にサポートしています。

こちら承知しました。

ただ、.javaファイルについて確認したところTest.java _Test.java共にUTF-8になっておりました。

Eclipseの設定としては、

[ウィンドウ] → [設定]からの「一般」 > 「ワークスペース」
テキスト・ファイル・エンコードは「UTF-8」

[ウィンドウ] → [設定]からの「一般」 > 「コンテンツ・タイプ」
でjavaファイルについては設定なし

[プロジェクト] → [プロパティー]からの「リソース」
テキスト・ファイル・エンコードは「UTF-8」

としています。

他に何か設定必要なものはございますでしょうか？

**Comment by yu-aoyama** [comment]
環境の問題かもしれないと考え、他のEclipse Mars(4.5.2) があったので確認してみたところ、こちらでは文字化けしませんでした。

改めてEclipse Neon(4.6.3)の
[ウィンドウ] → [設定]からの「一般」 > 「ワークスペース」
でテキスト・ファイル・エンコードを確認してみたところ「デフォルト(U)」で値が「MS932」になっているものを、「その他(O)」に変更して「UTF-8」にしていました。

ここの設定変更がうまく効いていないかと思い、eclipse.iniに以下

> -Dfile.encoding=utf-8

を設定してEclipseのデフォルトをUTF-8に変更したところ、文字化けしなくなりました！

「Eclipse 4.6.3」の問題なのか判断がつきませんが、ヒント頂けたおかげで解決しました。
ありがとうございました

doma-gen含めて素晴らしいフレームワークだと思いますので、これからも頑張ってください。
