### ISSUE TITLE
トランザクション終了後、 Connection の autoCommit が常に true に設定される

### ISSUE THREAD

**Issue by scnmztn** [domaframework/doma#233]
Connection の autoCommit が LocalTransaction#beginInternal で false に、 LocalTransaction#release で true に設定されますが、後者は true 固定ではなく beginInternal 以前の元の値とすべきかと思いますが、いかがでしょうか。

LocalTransactionConnection が preservedTransactionIsolation と同様に autoCommit 値を保持するようにするのが素直かなと思います。

**Comment by nakamura-to** [comment]
Doma 1の頃に同様の指摘をいただき、その時は対応を見送りました。
https://www.seasar.org/issues/projects/DOMA/issues/DOMA-315

再検討したいため、現在の実装でどんな問題が発生しているのか教えてもらえないでしょうか？

DataSourceとしてHikariCPのようなライブラリを使うと期待する挙動にできるかもしれません。
https://github.com/brettwooldridge/HikariCP/blob/HikariCP-3.2.0/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L210

**Comment by scnmztn** [comment]
迅速なリプライありがとうございます。

まず、当方では Doma2 + HikariCP + MySQL JDBC という組み合わせで Doma2 を利用させていただいております。

Doma トランザクションにおける autoCommit: false は正常に機能しており、クリティカルな問題が起きているわけではないのですが、パフォーマンス上の懸念があります。

まず、 MySQL JDBC ドライバーでは Connection#setAutoCommit によりデータベースサーバーに向けて SQL ステートメントが発行されるケースがあると認識しています ("SET autocommit=1" あるいは "SET autocommit=0") 。

現在の実装では HikariCP のコネクションプールにより Connection の再利用はできており、またご指摘のとおり autoCommit: false の設定も HikariCP レベルでは機能しているので Connection 返却時には元の autoCommit: false に戻ります。
問題として認識しているのは Doma の LocalTransaction によるトランザクション終了時の autoCommit: true と Connection 返却時の HikariCP による autoCommit: false がトランザクション毎に繰り返されることです。短時間のうちに小さなトランザクションが大量に発生するようなユースケースで、この autoCommit 切り替えによるオーバーヘッドがパフォーマンス上の深刻なボトルネックとなる可能性があると考えています。

オーバーヘッドの度合いは JDBC ドライバの実装に依存するため一概には言えないと思いますが、無視していいほど小さいものではないと考えたほうがよさそうです。

以上、ご検討いただけますと幸いです。

**Comment by nakamura-to** [comment]
ありがとうございます。懸念されている背景が良くわかりました。

もし可能であれば、MySQL JDBCでどれくらいのオーバーヘッドが発生しているのか検証していただくことはできますか？検証結果を基に修正を検討できればと思っています。

**Comment by scnmztn** [comment]
返信遅くなりました。
Connection#setAutoCommit のオーバーヘッドについて当方環境でざっくり計測してみましたのでご報告します。

**計測条件**
トランザクション開始, クエリ１件 (空テーブルに対する select 句, where 条件なし) 発行, トランザクション終了 を１セットとして所要時間を計測しました。 Connectino#setAutoCommit のオーバーヘッドあり／なしをそれぞれ１００回試行し、異常値は排除して平均所要時間を算出しました。
HikariCP を利用しているため物理コネクションの生成コストは含まれない認識です。

**計測結果**
- オーバーヘッドあり: 21.4ms
- オーバーヘッドなし: 14.6ms

絶対時間として深刻なレベルではありませんが、全体オーバーヘッドのうち setAutoCommit の占める割合がかなり高いものであるとは言えそうです。

**オーバーヘッドあり／なしの切り替えについて**
HikariCP より手前、 JDBC Driver の Connection 生成時に setAutoCommit(false) を実行し、またこの Connection をラップして以降の setAutoCommit を実際の Connection に移譲するか、無視するかを切り替えられるようにしました。

**実行環境**
- MySQL Server: version 5.7.20
- JDBC Driver: MySQL Connector 5.1.46
- Java クライアントと MySQL Server は同一 LAN 内の別マシンにて動作

**Comment by nakamura-to** [comment]
検証どうもありがとうございます 😃 
将来のバージョンでautoCommitの状態をトランザクション開始前の元の値に戻すようにしたいと思います。
もしPRいただけるならよろしくお願いします。
