### ISSUE TITLE
help about the use of [ @select(strategy=SelectType.STREAM]

### ISSUE THREAD

**Issue by nowsdt** [domaframework/doma#237]
`@Select(strategy = SelectType.STREAM)
BigDecimal selectByNameAndSalary(String name, BigDecimal salary, Function<Stream<Employee>, BigDecimal> mapper);`

I want to user @Select(strategy = **SelectType.STREAM**),but how to define the parameter mapper,and how to write the sql file.

`    @Select(mapKeyNaming = MapKeyNamingType.LOWER_CASE)
    public List<Map<String, Object>> getPatientCrfDetailValuePerGroup(
            List<ExportTemplateDetailDto> exportTempDetailList, PatientCrfDetailByTemplateDto queryDto,  String userId, String repeatGroup);`

the select method ‘getPatientCrfDetailValuePerGroup’，if I want to add the annotation  [strategy = SelectType.STREAM], like this:

` @Select(mapKeyNaming = MapKeyNamingType.LOWER_CASE,**strategy = SelectType.STREAM**)
    public List<Map<String, Object>> getPatientCrfDetailValuePerGroup(
            List<ExportTemplateDetailDto> exportTempDetailList, PatientCrfDetailByTemplateDto queryDto,  String userId, String repeatGroup);`

how to rewrite the select method [getPatientCrfDetailValuePerGroup]
     I‘m’ expecting a reply，thank you

**Comment by nakamura-to** [comment]
You can rewrite your method as followings:

```java
@Select(mapKeyNaming = MapKeyNamingType.LOWER_CASE, strategy = SelectType.STREAM)
public <R> R getPatientCrfDetailValuePerGroup(
    List<ExportTemplateDetailDto> exportTempDetailList,
    PatientCrfDetailByTemplateDto queryDto,
    String userId,
    String repeatGroup,
    Function<Stream<Map<String, Object>>, R> mapper);
```

`@Select(SelectType.STREAM)` has nothing to do with the sql file. Write is as usual.

**Comment by nakamura-to** [comment]
Let me show you a simple example.

Dao:

```java
@Dao
interface TweetDao {
    @Select(strategy = SelectType.STREAM)
    <R> R processUserTweets(
        String userId,
        Function<Stream<Tweet>, R> mapper);  
}
```

Service:

```java
public class TweetService {
    ...

    public Character findMostUsedCharacter(String userId) {
        return userDao.processUserTweets(userId, tweetStream -> {
            // handle many tweets
            ...
        });
    }
}
```

The mapper is used to handle a large amount of data without out of memory error.
Pass it as a lambda expression from service to dao.

**Comment by nowsdt** [comment]
@nakamura-to 
 got it, thank you！
