### ISSUE TITLE
How can I use an interface as @ExternalDomain for Iterable parameter in Dao?

### ISSUE THREAD

**Issue by yonekawa** [domaframework/doma#238]
For example:

```java
public interface Foo {
  Long getValue();

  static Foo of(Long value) {
     return new ConcreteFoo(value)
  }
}

@ExternalDomain
public class FooConverter implements DomainConverter<Foo, Long> {
    @Override
    public Long fromDomainToValue(Foo foo) {
        return foo.getValue();
    }

    @Override
    public Foo fromValueToDomain(Long value) {
        if (value == null) {
            return null;
        }
        return Foo.of(value);
    }
}

@Dao
public interface FooDao {
    @Select
    List<BarEntity> findBarByFoo(List<Foo> fooList);
}
```

When I call `findBarByFoo`, I encountered [DOMA2118].

```
org.seasar.doma.internal.jdbc.scalar.ScalarException: [DOMA1007] 型[ConcreteFoo]の値[Foo{value=0}]に対応するラッパークラスが見つかりません
```

I can use the interface if not Iterable: `List<Bar> findBarByFoo(Foo foo)`.
And I can use the interface for Entity attribute.

I guess that [this code](https://github.com/domaframework/doma/blob/bbf193b23437493f0b814a314cc2e7118dc817f8/src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java#L326) passes a concrete class object to Scalars.

Can I use domain value object for list parameter in Dao?

**Comment by nakamura-to** [comment]
OK, I see your situation.

I'm going to fix it this weekend.
The fix will be included in Doma 2.x.

**Comment by nakamura-to** [comment]
Doma 2.19.3 is out 😄 
The fix is included in it.
Try it and let me know if it doesn't work.
