### ISSUE TITLE
Insert時にIDが挿入もしくは更新されない

### ISSUE THREAD

**Issue by tasuku-s** [domaframework/doma#302]
いつもお世話になっております。
少々不可解な挙動があったので報告させていただきました。
DBにはPostgreSQLを利用しています。

以下のようなエンティティとDaoを定義していたとします。

```java
@Entity
public class Hoge {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  public Integer id;

  public String name;
}

@Dao
public interface HogeDao {
  ＠Insert
  int insert(Hoge hoge);
}
```

このとき、`Hoge.id` に前もってシステム外で定義した値を入れた状態で`HogeDao.insert`に渡すと、
 insert文にidが含まれず、エンティティにも新規生成されたIDがセットされないようです。

期待される動作としては、

1. idが指定されていた(nullでも0未満の値でもない)場合、insert文にidが含まれる
2. 問答無用で新規作成されたIDがエンティティにセットされる

のどちらかかなーという気がしますが、いかがでしょうか？

ちなみに、`@BatchInsert`の場合は前者の挙動になるようです。

**Comment by nakamura-to** [comment]
`GenerationType.IDENTITY` の指定がある場合、今はデータベースで生成させることを前提としてinsert文にidを含めていません。PostgreSQLでは確かそのようなSQLを発行しない限りデータベース側で生成されなかったと認識しています。Domaはinsert文を発行後に別のSQLでidを取得しているはずですが、エンティティにはすでに別の値がセットされているの上書きをしていないのだと思います。

> 1. idが指定されていた(nullでも0未満の値でもない)場合、insert文にidが含まれる

PostgreSQLでは、そのようなSQLを発行してもエラーにならないですか？この辺りの挙動はデータベースごとに異なっていた気がしますので悩ましいですね。`@BatchInsert`の挙動に合わせると1が望ましい気がしますが、複数のデータベースで挙動を合わせるなら2がいいような気もします。

> ちなみに、`@BatchInsert`の場合は前者の挙動になるようです。

#98 の対応でDomaがデータベースからidの値を一括で取得した後にinsert文を発行するようになったからですね。

**Comment by tasuku-s** [comment]
> > 1. idが指定されていた(nullでも0未満の値でもない)場合、insert文にidが含まれる
> 
> PostgreSQLでは、そのようなSQLを発行してもエラーにならないですか？

はい、PostgreSQL でIDENTITYに対応するカラムを作る場合、
`PRIMARY KEY`の型を`SERIAL`にしますが、その場合
`id INTEGER NOT NULL DEFAULT nextval('hoge_id_seq') PRIMARY KEY`と同値になります。
（`hoge_id_seq`というシーケンスも同時に生成されます)
https://www.postgresql.jp/document/10/html/datatype-numeric.html#DATATYPE-SERIAL

なので、idカラムがない場合には次のシーケンス値が入り、idカラムがある場合は指定されている数値が入ります。
ただ、後者の場合にはシーケンス値がインクリメントされないので、現在シーケンスの値が1の場合にid:1のデータを直接入れると、次回インサート時にIDが重複してコケます。

DBによっては事前にIDの値が取得可能できないか、インサート時にidを含めることができない可能性があるということですかね？
そうでなければ採番タイミングを事前にすれば統一はできそうな気がしますが、難しそうですね・・・

**Comment by nakamura-to** [comment]
> ただ、後者の場合にはシーケンス値がインクリメントされないので、現在シーケンスの値が1の場合にid:1のデータを直接入れると、次回インサート時にIDが重複してコケます。

なるほど。ということだと1の案を採用したとしても望ましくない挙動を引き起こしうるのですね。

> DBによっては事前にIDの値が取得可能できないか、インサート時にidを含めることができない可能性があるということですかね？

そうです。SQL Serverの場合、自動生成されるidを明示的にセットするにはinsertの実行前に別のコマンドを発行しておかないとエラーになります。
https://docs.microsoft.com/ja-jp/sql/t-sql/statements/set-identity-insert-transact-sql?view=sql-server-2017

（ちなみに、エラーを回避するためにこのようなコマンドをDomaが勝手に発行するのは望まれていない気がします）

> このとき、`Hoge.id` に前もってシステム外で定義した値を入れた状態で`HogeDao.insert`に渡すと、

念のため確認させてもらいたいのですが、上記のようなことを実際のアプリケーションで実現したくて困っているわけではないですよね？ エンティティに `GenerationType.IDENTITY` の設定をしているのなら、値をセットせずに `@Insert` のメソッドに渡すのが通常の使い方です 😄

**Comment by tasuku-s** [comment]
実は、実際のアプリケーションで実現しております・・・(回避策はあるので困っているわけではありません)
やりたかったことは、「サービススタート前に事前に集めたデータをアプリケーションを通して入れておく(ちょっと複雑な処理が入るのでDB直入れは避けたかった)」です。
シーケンスのスタート値を 100000 としておいて、それ未満の値を初期データ用にとっておき、ID固定で処理できるようにしようとしました。
その際、`@Insert`でやるとうまくidが入らずエンティティに上書きもされず、`@BatchInsert`でやるとidが入ることに気づいた、という経緯です。

**Comment by nakamura-to** [comment]
なるほど、実際に使われているんですね。
IDを固定してinsertしたいことはありますよね。私も経験があります。

もし綺麗に実現するならですが、 `GenerationType.IDENTITY` の指定がないエンティティクラスにデータをコピーしてinsertしてもいいかもしれないですね。（別のクラスを用意するのが少し手間ですが）

このissueの扱いですが以下の2択かなと思っています。

1. 仕様ということで特に何も対応せずこのままクローズ
2. 問答無用で新規作成されたIDがエンティティにセットされるように修正する

2番目の選択肢は、そういう挙動になったところで必ずしも利点があるのか不明です。もしこっちを選ぶならもう少し利点を明確化したいなと感じています。

**Comment by tasuku-s** [comment]
そうですね、1で大丈夫かと思います。
ありがとうございました。
