### ISSUE TITLE
How can I get AutoIncrement ID on Insert with SQL files

### ISSUE THREAD

**Issue by kamitath** [domaframework/doma#317]
Doma2ではSqlFileInsertQueryの場合generateIdで何もしないためEntityにAuto increament の IDが付与されませんが、Insert時にsql fileを利用した状態でAuto increment の IDを取得する推奨の実装はありますでしょうか？ 
もし実施したい場合はjdbcを直で使って自前実装するしかないでしょうか？
以上お手数ですがよろしくお願いいたします。

**Comment by nakamura-to** [comment]
> Insert時にsql fileを利用した状態でAuto increment の IDを取得する推奨の実装はありますでしょうか？

サポートしていないです。

> もし実施したい場合はjdbcを直で使って自前実装するしかないでしょうか？

どうしてもSQLを自前で組み立てたいならそうなりますね。

ただ、次の2点は改めて検討してみてもいいと思います。
- IDの採番にauto incrementではなくsequenceを使う
- `@Insert(sqlFile = false)` を使う

sql fileを使ってinsert文を組み立てたい理由は何でしょうか？背景を教えてもらえると別の方法を提案できるかもしれません。

**Comment by kamitath** [comment]
ご返答ありがとうございます。

sql fileを使ってinsert文を組み立てたい理由としては、水平分割テーブル構造にDBがなっていまして、
`insert into data_/*# tableNo */_tbl ( ~~~`
のような形でtable の 番号を動的に変化させたinsert文を発行したいというのが理由になります。

以上よろしくお願いいたします。

**Comment by nakamura-to** [comment]
なるほど。
ちょっと愚直ですが、テーブルの数だけEntityやDaoメソッドを用意してしまうのは一つの方法です。

```java
@Entity
public abstract class Address { ... }

@Entity @Table(name = "address_1")
public class Address1 extends Address {}

@Entity @Table(name = "address_2")
public class Address2 extends Address {}

@Dao
public interface AddressDao {
    @Insert
    int insert(Address1 entity);
    @Insert
    int insert(Address2 entity);
}
```

もう一つはinsert文の自動生成ロジックを上書きしてテーブル名称を差し替えてもいいと思います。insert文のテーブル名を設定しているのはここです。
https://github.com/domaframework/doma/blob/2.24.0/src/main/java/org/seasar/doma/jdbc/query/AutoInsertQuery.java#L123
`org.seasar.doma.jdbc.QueryImplementors#createAutoInsertQuery` で `AutoInsertQuery` のサブクラスを返す感じにしてもらえれば実現できると思います。
今はinsert文の自動生成ロジック全体を上書きしてもらう必要がありますが、将来的にはテーブル名だけを上書きできるようにメソッドを分割してもいいと思っています。

**Comment by kamitath** [comment]
ありがとうございます！
試してみます！

ご回答ありがとうございました！
解決したのでCloseいたします。
