### ISSUE TITLE
How can I use myself entity to create daoImpl

### ISSUE THREAD

**Issue by LAngelsFree** [domaframework/doma#318]
I have a question about Doma2.
 When I set up dao.package into Annotation Processing,【 _Entity 】【 daoImpl 】were both created.So How can I used myself entity to just create【 daoImpl 】instead of both created.
 Thanks~

**Comment by nakamura-to** [comment]
It's almost impossible. Both are essential parts of Doma. 
Could you show me an example code? 
Then I could say something useful to you.
