### ISSUE TITLE
Needs default constructor to AbstractDao to use quarkus

### ISSUE THREAD

**Issue by jirokun** [domaframework/doma#332]
I'm working on quarkus framework using CDI and Doma2.
CDI requires default constructor to use constructor injection.
But AbstractDao and generated source code do not have default constructor.

Details as follows
https://quarkus.io/blog/quarkus-dependency-injection/

**Comment by nakamura-to** [comment]
OK. 
We are going to generate a no-args constructor if a Dao interface is annotated with `@ApplicationScoped`: 

```java
@Dao
@ApplicationScoped
interface EmployeeDao { ... }
```

```java
// generated code
class EmployeeDaoImpl extends AbstractApplicationScopedDao implements EmployeeDao { 
  // no-args constructor
  EmployeeDaoImpl() {}
}
```


See #333.

However, should we consider not only `@ApplicationScoped` beans but also all normal scoped beans? In other words, should we check `@javax.enterprise.context.NormalScope`?

Please let us know what you think.

**Comment by nakamura-to** [comment]
Ah, should `@ApplicationScoped` annotated not for a Dao interface, but for a generated code？

**Comment by jirokun** [comment]
I want to use with following way.

```java
@Dao
@AnnotateWith(annotations = [
    Annotation(target = AnnotationTarget.CLASS, type = ApplicationScoped::class),
    Annotation(target = AnnotationTarget.CONSTRUCTOR, type = Inject::class)
])
interface BookDao {
    @Select
    fun selectAll(): List<Book>
}
```

I believe that supporting ApplicationScoped is sufficient in most cases.
In addition, the Dependent class is available now.

```java
@Dao
@AnnotateWith(annotations = [
    Annotation(target = AnnotationTarget.CLASS, type = Dependent::class),
    Annotation(target = AnnotationTarget.CONSTRUCTOR, type = Inject::class)
])
interface BookDao {
    @Select
    fun selectAll(): List<Book>
}
```

**Comment by nakamura-to** [comment]
Thanks for your reply. We'd like to support your usecase.

**Comment by nakamura-to** [comment]
@jirokun We have a question.

> But AbstractDao and generated source code do not have default constructor.

Should we provide a default constructor for "only AbstractDao" or "both AbstractDao and generated source code"?

If "only AbstractDao" requires a default constructor, it's very simple to change Doma.

**Comment by jirokun** [comment]
Probably it need constructors for AbstractDao and GeneratedSource.

Here is the source code I'm making.
https://github.com/domaframework/doma/pull/335

**Comment by nakamura-to** [comment]
Thanks for your answer and pull request.
We are considering to include #334.

**Comment by nakamura-to** [comment]
The super gentleman @backpaper0 gave me an advice:
https://twitter.com/backpaper0/status/1219014715902287872

He said that only AbstractDao should have a default constructor.
We merged #336.

**Comment by nakamura-to** [comment]
We found #336 didn't work well.
So we accepted #337.

**Comment by nakamura-to** [comment]
We remove Dependent annotation support at 70d320ab8f13a91bebf427986ab41656fa34f534.
A default constructor is generated only when a DaoImpl is annotated with ApplicationScoped annotation.

**Comment by nakamura-to** [comment]
You can specify the ApplicationScoped annotation to generated code with `@AnnotateWith` as flollows:

```java
@Dao
@AnnotateWith(annotations = {
    @Annotation(target = AnnotationTarget.CLASS, type = ApplicationScoped.class)
    @Annotation(target = AnnotationTarget.CONSTRUCTOR, type = Inject.class) })
public interface EmployeeDao { 
    ...
}
```

The generated code is as follows:
```java
@ApplicationScoped()
public class EmployeeDaoImpl extends org.seasar.doma.internal.jdbc.dao.AbstractDao implements EmployeeDao {

    EmployeeDaoImpl() {
    }

    @Inject
    public EmployeeDaoImpl(Config config) {
        super(config);
    }
}

```
