### ISSUE TITLE
基本型を複数件返却するストアドファンクションの戻り値がnullになる

### ISSUE THREAD

**Issue by yoshy0407** [domaframework/doma#345]
概要
---
以下のような基本型を複数件返却するストアドファンクションをDaoインターフェースに定義して実行すると、戻り値がnullになって返却されます。
（ストアドファンクションは基本型を複数件返却するものを指定しています。）

```
@Function
public List<String> exetcuteList(@In String num);
```

これは仕様でしょうか？それともバグでしょうか？ご確認お願いします。

動作環境
---
Oracle JDK 1.8.0_202
Doma 2.27.1
Oracle Database

## 補足
私の方でも処理結果を追ってみたのですが、`ScalarResultListParameter#getResult`で`null`を返却しているからではないかと。
（ザーッと見た感じだと、`DomainResultListParameter`なども上記クラスを継承しているので、影響があるのではないかと思います。）

**Comment by nakamura-to** [comment]
フィードバックありがとうございます。これはバクですね。

補足で指摘いただいた通り、`ScalarResultListParameter#getResult`で`null`を返しているのが問題でした。

**Comment by nakamura-to** [comment]
修正をした Doma 2.28.0 をリリース済みです。

**Comment by yoshy0407** [comment]
ありがとうございます。
2.28.0を利用させていただきます
