### ISSUE TITLE
Doma2のListをバインドできない？

### ISSUE THREAD

**Issue by mizo432** [domaframework/doma#383]
Doma2を利用しての開発中に出ている意味不明なコンパイルエラーです。
コンパイルエラーメッセージを読んだのですが、なにかヒントがあれば教えてください。
パラメータはイテラブルまたは配列のさぶたいぷでなければならないが、java.util.Listです。
というように読み取ったのですが、読み取り方が間違っていますか？
‘‘‘
domaVersion = '2.29.0'

エラー: [DOMA4161] Failed to verify the SQL template "META-INF/net/jagunma/chikusan/model/dao/bikou/BikouEntityDao/findOneBy.sql" on line 16 at column 113. The parameter type that corresponds to the expression "criteria.bikouIdCriteria.includes" must be a subtype of either java.lang.Iterable or an array type. But the actual type is "java.util.List". You may forget to access to its field or to invoke its method. SQL=[select
*
from
dbo.Bikou
where
1 = 1
/*%if criteria.bikouIdCriteria.equalTo != null*/AND BikouId = /*criteria.bikouIdCriteria.equalTo*/0/*%end*/
/*%if criteria.bikouIdCriteria.notEqualTo != null*/AND BikouId != /*criteria.bikouIdCriteria.notEqualTo*/0/*%end*/
/*%if criteria.bikouIdCriteria.isNull != null*/AND BikouId is null /*%end*/
/*%if criteria.bikouIdCriteria.isNotNull != null*/AND BikouId is not null/*%end*/
/*%if criteria.bikouIdCriteria.moreThan != null*/AND  /*criteria.bikouIdCriteria.moreThan*/0 < BikouId/*%end*/
/*%if criteria.bikouIdCriteria.moreOrEqual != null*/AND  /*criteria.bikouIdCriteria.moreOrEqual*/0 <= BikouId/*%end*/
/*%if criteria.bikouIdCriteria.lessThan != null*/AND BikouId < /*criteria.bikouIdCriteria.lessThan*/0/*%end*/
/*%if criteria.bikouIdCriteria.lessOrEqual != null*/AND BikouId <= /*criteria.bikouIdCriteria.lessOrEqual*/0/*%end*/
/*%if criteria.bikouIdCriteria.from != null && criteria.bikouIdCriteria.to != null*/AND BikouId between /*criteria.bikouIdCriteria.from*/0 and /*criteria.bikouIdCriteria.to*/1/*%end*/
/*%if criteria.bikouIdCriteria.includes.isEmpty() != true*/AND BikouId in /*criteria.bikouIdCriteria.includes*/(0)/*%end*/
/*%if criteria.bikouIdCriteria.excludes.isEmpty() != true*/AND BikouId not in /*criteria.bikouIdCriteria.excludes*/(0)/*%end*/

 ... /** The SQL statement is too long. The only first 5,000 character are displayed. */]

‘‘‘

SQLが続くのでメッセージは短くしてます。

**Comment by nakamura-to** [comment]
"criteria.bikouIdCriteria.includes" に対応するクラスやフィールドの定義を見せてもらってもいいでしょうか？関連するところの抜粋だけで良いです。

**Comment by mizo432** [comment]
抜粋です。

Getterはあります

``` Java
public class BikouEntityCriteria  extends AbstractCriteria<BikouEntity> {
    private LongCriteria bikouIdCriteria = new LongCriteria();
    private StringCriteria bikouCodeCriteria = new StringCriteria();
    private StringCriteria bikouNameCriteria = new StringCriteria();
    private IntegerCriteria sakujosumiFlagCriteria = new IntegerCriteria();

    public boolean test(BikouEntity aValue) {
        return super.test(aValue)
            && bikouIdCriteria.test(aValue.getBikouId())
            && bikouCodeCriteria.test(aValue.getBikouCode())
            && bikouNameCriteria.test(aValue.getBikouName())
            && sakujosumiFlagCriteria.test(aValue.getSakujosumiFlag());
    }

}
```

Getterはあります

``` Java
public class LongCriteria extends AbstractCriteria<Long> {
    private Long moreThan;
    private Long moreOrEqual;
    private Long lessThan;
    private Long lessOrEqual;
    private Long from;
    private Long to;
    @Override
    public boolean test(Long aValue) {
        return super.test(aValue) &&
                MoreThanPredicate.of(moreThan)
                        .and(MoreOrEqualPredicate.of(moreOrEqual))
                        .and(LessThanPredicate.of(lessThan))
                        .and(LessOrEqualPredicate.of(lessOrEqual))
                        .and(BetweenPredicate.of(from, to))
                        .test(aValue);

    }
}
```

``` Java
public abstract class AbstractCriteria<O> implements Serializable, Predicate<O> {
    private O equalTo;
    private O notEqualTo;
    private Boolean isNull;
    private Boolean isNotNull;
    private List<O> includes = newArrayList();
    private List<O> excludes = newArrayList();

    public List<O> getIncludes() {
        return includes;
    }

    // などなど

    @Override
    public boolean test(O aValue) {
        return EqualToPredicate.of(equalTo)
                .and(NotEqualToPredicate.of(notEqualTo))
                .and(IsNullPredicate.of(isNull))
                .and(IsNotNullPredicate.of(isNotNull))
                .and(IncludesPredicate.of(includes))
                .and(ExcludesPredicate.of(excludes))
                .test(aValue);

    }
}
'''

**Comment by mizo432** [comment]
AbstractCriteriaは最近足したので、影響がでているのかも・・・

**Comment by nakamura-to** [comment]
`List<O> includes` の`O`ような型パラメータを型引数を持ったListをIN句にバインドするのはサポートしていません。 `List<String>` の`String`など型引数がDomaがサポートする具体的な型であれば問題ありません。

エラーメッセージがわかりにくい点については改善したいと思います。

**Comment by mizo432** [comment]
型パラメータの件、承知しました。
ありがとうございます。

**Comment by nakamura-to** [comment]
もう少し調べたところ、今回のケースは対応できそうなことがわかりました。
つまり、`List<O>`の`O`が実際は`Long`だということが判定できました。
次のバージョンでサポートしたいと思います。
