### ISSUE TITLE
Cannot compile class entity generated by doma-processor in version > 2.28.0

### ISSUE THREAD

**Issue by ldcuong** [domaframework/doma#420]
My eclipse max 8GB memory but cannot finish compiler task.
Out of memory error when compile entity from .apt_generated.
Can you optimize generated class by doma-processor?

My project have 199 entity.
Each entity have min 200 column and max 500 column.

**Comment by nakamura-to** [comment]
Hi. Could you tell me more details?

- Which version of Java do you use?
- Which version of Eclipse do you use?
- Do you build your project with Gradle? And does it work without OutOfMemoryError?
- Where do you think the bottleneck is?
  - Is the constructor of the generated class too long?

**Comment by ldcuong** [comment]
Thank you for reply. @nakamura-to 

Which version of Java do you use?
-> I using Java 8
Which version of Eclipse do you use?
-> Eclipse version 2018-09(4.9.0) Build 20180917-1800
Do you build your project with Gradle? 
-> Yes I build project with Grade version 5.5.1
And does it work without OutOfMemoryError?
-> It's working on version DOMA 2.19.2 but OutOfMemory on latest version (2.34.0)
Where do you think the bottleneck is?
Is the constructor of the generated class too long?
-> I think because my entity have large column size so class entity generated by DOMA new large Object => OOM. (My eclipse setting 8GB memory for compile)

If you need more information, please inform me.

Thanks

**Comment by nakamura-to** [comment]
Thanks for your information.

I was able to reproduce the problem.
I will investigate the cause.

**Comment by nakamura-to** [comment]
I found the ClassName::new syntax was slow.
This fix will be included in next version.

**Comment by ldcuong** [comment]
@nakamura-to 
Wow, very fast.
Thank you for your hard working.
I waiting next version for using Criteria API.
