### ISSUE TITLE
Criteria APIもInsrtSettingsについて

### ISSUE THREAD

**Issue by hinoko58** [domaframework/doma#446]
https://doma.readthedocs.io/en/latest/criteria-api/#insert-settings-entityql-nativesql

をのサンプル(Entityql)を実行してみると

```
Department department = new Department();
department.setDepartmentId(99);
department.setDepartmentNo(99);
department.setDepartmentName("aaa");
department.setLocation("bbb");

Result<Department> result = entityql.insert(d, department).execute();
```

```
insert into DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NO, DEPARTMENT_NAME, LOCATION, VERSION)
values (99, 99, 'aaa', 'bbb', 1)
```
のSQLが発行されると思います。

https://github.com/domaframework/doma/blob/master/doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/EntityqlInsertStatement.java#L44

を見るとfalse固定なっていて@Insert(excludeNull=true)
バージョンは実装されていないように思いますが、方針ということでいいでしょうか？

**Comment by nakamura-to** [comment]
ニーズがあるか分からなかったのでとりあえずは未サポートとしましたが、要望あれば対応します。

なお、今でもNativeSqlの方を使えば `null` の時は対象外にするということは条件分岐を入れれば実現できますが、少し面倒かもしれません。

```java
int count =
    nativeSql
        .insert(d)
        .values(
            c -> {
              c.value(d.departmentId, 99);
              c.value(d.departmentNo, 99);
              c.value(d.departmentName, "aaa");
              if (location != null) {
                  c.value(d.location, location);
              }
              c.value(d.version, 1);
            })
        .execute();
```

**Comment by hinoko58** [comment]
迅速な回答ありがとうございます。

nativeSqlの方も見当しましたが、EntityListenerの機能がトリガーされないとの認識です。

方針ではない点理解しました。

**Comment by nakamura-to** [comment]
確かにEntityListenerはトリガーされないですね。
`@Insert(excludeNull=true)` 相当の機能は次のバージョンで提供しようと思います。

**Comment by hinoko58** [comment]
最高です。
ありがとうございます。
