### ISSUE TITLE
Update statement issued by NativeSQL causes an error in PostgreSQL

### ISSUE THREAD

**Issue by hk-atm** [domaframework/doma#537]
**Describe the bug**
Criteria API NativeSQL issues the following SQL statement:
```
update EMPLOYEE t0_ set t0_.DEPARTMENT_ID = ?
where t0_.MANAGER_ID is not null and t0_.SALARY >= ?
```
But PostgreSQL doesn't allow that a column name includes a table name in a SET clause.
see: https://www.postgresql.org/docs/current/sql-update.html

**Environment (please complete the following information):**
- Doma version or git rev: Doma 2.36

**Comment by nakamura-to** [comment]
Thank you for your feedback.
I will fix this issue.

**Comment by nakamura-to** [comment]
Try Doma 2.41.0.

**Comment by hk-atm** [comment]
I tried 2.41.0 and confirmed the bug has been fixed.
Thanks!
