### ISSUE TITLE
Mssql2008Dialect の getName が ドキュメントと異なる値を返している

### ISSUE THREAD

**Issue by OdaShinsuke** [domaframework/doma#56]
ドキュメントでは "mssql" を返すように書かれていますが、実際には "mssql2008" を返しています。

ドキュメント
http://doma.readthedocs.org/ja/2.1.0/sql/?highlight=mssql#id7
ソース
https://github.com/domaframework/doma/blob/master/src/main/java/org/seasar/doma/jdbc/dialect/Mssql2008Dialect.java#l128

**Comment by nakamura-to** [comment]
ご指摘ありがとうございます。
たしかに間違っていますね。
プログラムで"mssql"と"mssql2008" のどちらを返すべきか、ご意見ありますか？

現時点の私の考えでは、"mssql"を返すように修正しようと思っています。

**Comment by OdaShinsuke** [comment]
SQL ファイルの切り替えに使われる値ですよね？
私も "mssql" で良いと思います。

**Comment by nakamura-to** [comment]
> SQL ファイルの切り替えに使われる値ですよね？

はい、そうです。
では、"mssql"を返すように修正しようと思います。
