### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by webfolderio** [domaframework/doma#588]
**Description**
It will be nice to add CHANGELOG.md/RELEASENOTE.md to repository.

**Comment by nakamura-to** [comment]
Release notes are available [here](https://github.com/domaframework/doma/releases).
But do you want to get them as a markdown file?

**Comment by webfolderio** [comment]
Thanks for the link but it might be nice to read single file and this is more SEO friendly.

**Comment by nakamura-to** [comment]
CHANGELOG.md is now available.
We keep it in sync with the GitHub release page.

**Comment by webfolderio** [comment]
This is great, thanks.
