### ISSUE TITLE
SQL Server MERGE statement needs an explicit ";"(semi-colon) at the end of the statement

### ISSUE THREAD

**Issue by sgrit** [domaframework/doma#620]
**Description**
In SQL Server, we can omit ";" for SELECT, UPDATE, INSERT or DELETE statement, but it looks we cannot omit ";" in MERGE statement.
SQL Server MERGE statement needs an explicit ";"(semi-colon) at the end of the statement, but it seems DOMA removes ";" in the sql file.

**Implementation ideas**
";" at the end of file should retain (for SQL Server's MERGE statement) instead of removing it. (if sqlfile = true)
or creating a configuration item so that user can choose sanitizing ";" or retaining ";".

**To Reproduce**
1. Execute following sql file with "@BatchInsert" (may be @Insert is not working either.);
```
MERGE INTO
    User
USING
    (
    SELECT
        /* users.id */'XXXXXXXXXXXXXXXXX' as ID
    ) AS Target
ON
    (
    [User].[ID] = [Target].[ID]
    )
WHEN MATCHED THEN
    UPDATE SET
        Name = /* users.name */

WHEN NOT MATCHED THEN
    INSERT
    (
        [ID],
        [Name]
    )
    VALUES
    (
        /* users.id */'XXXXXXXXXXXXXXXXX',
        /* users.name */'Takashi'
    )
;
```

2. Get a java.sql.BatchUpdateException with following error message.
``` The cause is as follows: java.sql.BatchUpdateException: A MERGE statement must be terminated by a semi-colon (;).. ```

**Environment (please complete the following information):**
- Doma version or git rev: 2.29.0
- Database version: SQL Server 12.0.2000
- JDBC Driver version: com.microsoft.sqlserver:mssql-jdbc:8.4.1.jre8

**Additional context**
I'm not sure if this may cause security issues, but I appreciate if you would look into this request.

**Comment by nakamura-to** [comment]
Thanks for your detailed feedback!
We fixed this issue.
