### ISSUE TITLE
[BUG] NativeSql DSl returning wrong type for Optional properties on selecting

### ISSUE THREAD

**Issue by wbprime** [domaframework/doma#627]
**Describe the bug**
Given entity class:

```java
@Entity(metamodel = @Metamodel)
@Table(name = "users")
public class User {
    @Column(name = "upd_time")
    private Optional<LocalDateTime> updatedAt;
}
```

and invoking case:

```java
private final User_ meta = new User_();
final NativeSql dsl = new NativeSql(config);
final Optional<LocalDateTime> latestUpdateTime = config.getTransactionManager().required(
        () -> dsl.from(meta ).select(Expressions.max(meta.updatedAt)).fetchOptional()
);
```

The real type of `latestUpdateTime` is `Optional<Optional<LocalDateTime>>`.  e.g., when no records found in db, `Optional.of(Optional.empty())` is returned. So it will cause ClassCast exception when using that var.

**Expected behavior**
The real type of `latestUpdateTime` is `Optional<LocalDateTime>`. e.g., when no records found in db, `Optional.empty()` should be returned.

**Actual behavior**
The real type of `latestUpdateTime` is `Optional<Optional<LocalDateTime>>`.  e.g., when no records found in db, `Optional.of(Optional.empty())` is returned.

**To Reproduce**
See previous description.

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
- Doma version or git rev: 2.44.0
- IDE version (ie. Eclipse or IntelliJ IDEA): IntelliJ IDEA
- Output of `java -version`:
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
- Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
- Database version: MySQL 5.7 and H2
- JDBC Driver version: mysql:mysql-connector-java:8.0.212 and com.h2database:h2:1.4.1972

**Additional context**
(Add any other context about the problem here.)

**Comment by nakamura-to** [comment]
Thanks for your detailed feedback.
I'll investigate it.

**Comment by nakamura-to** [comment]
We fixed this bug.
Try Doma 2.44.2.
