### ISSUE TITLE
Feature request: Add named expression

### ISSUE THREAD

**Issue by orekyuu** [domaframework/doma#641]
**Description**
For example, it is not DRY to write the condition that you are over 18 years old with multiple SQLs as follows.

example:
```sql
select * from users where age > 18;
select * from users where age > 18 and role ='customer'
```

When using Eintityql, the age condition is defined by the following static factory method.

```java
static Consumer<WhereDeclaration> onlyAdult(PropertyMetamodel<Integer> ageProp) {
  return w -> { w.gt(ageProp, 18) };
}

Entityql entityql;
UserEntity_ e;

// select * from users where age> 18;
entityql.from(e).where(onlyAdult(e.age));

// select * from users where age> 18 and role = 'customer';
entityql.from(e).where(onlyAdult(e.age).andThen(w -> { w.eq(e.role, 'customer') }));
```

I want to define methods in the Criteria API instead of mass-producing factory methods.

**Implementation ideas**
How about delegate from a generated class to a specific class?

example
```java
@Entity
@Scoped(UserEntityScope.class) // The method defined in this class is generated in UserEntity_
class UserEntity {
  Integer age;
  String role;
}

public class UserEntityScope {
  public Consumer<WhereDeclaration> onlyAdult(UserEntity_ e) {
    return w -> { w.gt(e.age, 18) };
  }
}
```

Generated image:
```java
class UserEntity_ {
  UserEntityScope userEntityScope = new UserEntityScope();
  // ...
  
  public Consumer<WhereDeclaration> onlyAdult() {
    return userEntityScope.onlyAdult(this);
  }
}
```

**Referenced**
The named expression is provided in ActiveRecord under the name scope: https://railsguides.jp/active_record_querying.html#%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97

**Comment by orekyuu** [comment]
If there is no problem with the idea, I would like to implement it. 😃

**Comment by nakamura-to** [comment]
Thanks for your request.
Your idea is exciting!

How about enhancing the `@Metamodel` annotation instead of introducing the `@Scope` annotation.

```java
@Entity(metamodel = @Metamodel(scope = UserEntityScope.class))
class UserEntity {
  Integer age;
  String role;
}
```

**Comment by orekyuu** [comment]
Thanks.
I will implement it with that plan.

**Comment by nakamura-to** [comment]
If you have any questions, feel free to contact us.
You can use our [chatroom](https://domaframework.zulipchat.com/).
