### ISSUE TITLE
Nested Entity classes

### ISSUE THREAD

**Issue by dtha1002** [domaframework/doma#657]
I am beginner with Doma and Spring Boot. So, sorry for my mistake.
I have 2 entities to map SQL's result. I want to nest entities as below:

**UserEntity Class**
```
@Entity
@Table(name = "user")
public class UserEntity implements Serializable {
    private static final long serialVersionUID = 1L;
    
    @Id
    @Column(name = "name")
    private String name;

    @Column(name = "message")
    private String message;
    
    //getter&setter
}
```

**GroupEntity Class**
```
@Entity
public class GroupEntity implements Serializable {
    private static final long serialVersionUID = 1L;
    
    private String group;
    
    private List<UserEntity> users;
    
    //getter&setter
}
```

Error: List<UserEntity> is not supported as a persistent type. If you intend to map the class to the external domain class with @ExternalDomain, the configuration may be not enough. Check the class annotated with @DomainConverters and the annotation processing option "doma.domain.converters".

How to insert UserEntity inside GroupEntity? 
Thanks for help!

**Comment by nakamura-to** [comment]
Hi.

Use `org.seasar.doma.Transient` annotation as follows:

```java
@Transient
private List<UserEntity> users = new ArrayList<>();
```

You can find sample code in the [spring-boot-jpetstore](https://github.com/domaframework/spring-boot-jpetstore) repository.

Entity definition:
https://github.com/domaframework/spring-boot-jpetstore/blob/b364d898544743d7891656617158efd4c3a0bdc3/src/main/java/sample/entity/Order.java#L84

Query:
https://github.com/domaframework/spring-boot-jpetstore/blob/b364d898544743d7891656617158efd4c3a0bdc3/src/main/java/sample/repository/OrderRepository.java#L25-L47

Insert:
https://github.com/domaframework/spring-boot-jpetstore/blob/b364d898544743d7891656617158efd4c3a0bdc3/src/main/java/sample/repository/OrderRepository.java#L62-L72

See [Criteria API](https://doma.readthedocs.io/en/latest/criteria-api/) for more detail.

**Comment by dtha1002** [comment]
It works very well.
I have found a very helpful article of you.
https://qiita.com/nakamura-to/items/b16cbed6edc2b7aaac47

Thank you very much for your help!
