### ISSUE TITLE
SelectBuilder以外にもparams メソッドと literals メソッドを追加

### ISSUE THREAD

**Issue by lunch2000** [domaframework/doma#679]
表題の通り、`InsertBuilder` `UpdateBuilder` `DeleteBuilder` にも `params` メソッドと `literals` メソッドを追加する予定はないでしょうか。

**Comment by nakamura-to** [comment]
ニーズがあるとは想定していなかったので予定はないです。
追加を希望されていると言うことでしょうか？
もし希望されるならどのような背景で必要としているのか聞いてみたいです。

**Comment by lunch2000** [comment]
はい。追加を希望しています。

```sql
insert into temp_table( 
    id,
    name,
    description
)
select
    id,
    name,
    description
from
    base_table
where
    name in ( 'a', 'b', 'c')
;
```

のようなクエリを組み立てるときに、paramsがあると助かるんです。
updateやdeleteの条件も同様です。
