### ISSUE TITLE
Some NativeSQL set queryTimeout to fetchSize

### ISSUE THREAD

**Issue by hk-atm** [domaframework/doma#720]
**Describe the bug**
I found that queryTimeout values is set to fetchSize at:

- org.seasar.doma.jdbc.criteria.statement.NativeSqlSetTerminal#createCommand
- org.seasar.doma.jdbc.criteria.statement.NativeSqlSelectTerminal#createCommand

I just investigate the source code, but didn't test it.

**Environment (please complete the following information):**
- Doma version or git rev: 2.47.1

**Comment by nakamura-to** [comment]
Thanks for your feedback!
