### ISSUE TITLE
Criteria Apiについて、leftJoinの条件の書き方

### ISSUE THREAD

**Issue by xweiqingfei1** [domaframework/doma#728]
Criteria Apiを追加って下記のようなSQLはどうやって書きますか？
```
select
  a.*
from
tableA a
left join tableB b on
  b.col1 = a.col1
  and b.col2 is not null
where
  a.col3 = 1
```
entityql.from(a).leftJoin(b, on->{
  on.eq(b.col1, a.col1)
  on.isNotNull(b.col2)                //<-このメソッドが存在しないです。
})

暫定対応はSQLを変更して、subqueryでやらないといけないらしいです。
```
select
  a.*
from
tableA a
left join (
select
  *
from tableB
where
  col2 is not null
) b on
  b.col1 = a.col1
where
  a.col3 = 1
```
ネットでいろいろ調べましたが、解決方法を見つけませんでした。

**Comment by nakamura-to** [comment]
フィードバックありがとうございます。

今はON句で`isNull`や`isNotNull`をサポートしていませんが、次のバージョンでサポート予定です。
次のように記述できるようにします。

```java
entityql.from(a).leftJoin(b, on->{
  on.eq(b.col1, a.col1);
  on.isNotNull(b.col2);
  on.isNull(b.col3);
});
```

**Comment by gikeihi** [comment]
ありがとうございます。
