### ISSUE TITLE
left joinについて

### ISSUE THREAD

**Issue by gikeihi** [domaframework/doma#736]
**Description**
下記の対応、ありがとうございました。
[Support isNull and isNotNull predicates in ON clause of Criteria API](https://github.com/domaframework/doma/pull/729)
よく考えると、ON clauseはwhere clauseとあまり変わらないではないかと思います。
inner joinはjoin対象テーブルの条件はONの代わりに、Whereに入れても大丈夫ですが、
left outer joinの場合、join対象テーブルの条件は必ずONに入れないといけないですよね。
例えば
```
select
a.*,
b.*
from
a
left join b on(
b.id = a.id
and b.col1 is null
and b.col2 is not null
and (
   b.col3 like '%aa%'
   or b.col4 not like '%bb%'
)
and b.col5 in (1,2,3,4)
and b.col6 not in (1,2,3,4)
and b.col7 between 1 and 10
...................
)
```

**Comment by nakamura-to** [comment]
そうですね。inner joinの場合は条件をon句に指定してもwhere句に指定しても結果は変わらないですが、left joinの場合は結果が変わりますね（on句に指定したい場合がありますね）。

ところで、このissueは不具合の報告ではないということでよろしいでしょうか？意見交換や議論についてはオリジナルのissueである #728 のコメント欄か [discussions](https://github.com/domaframework/doma/discussions) を活用できればと思っています 😃

**Comment by gikeihi** [comment]
そうですよね。
`Bug report`ではなく、`Feature request`です。

**Comment by gikeihi** [comment]
`「on句でwhere句と同様に様々な条件を指定できるようにしてほしい」`
はい、そういうことです。
上記の例は説明するため、書いた極める複雑なSQL、実際はあまりないと思います。

実際は、下記のような仕様があります。
テーブルAには、「部署ID」という項目があります、ただ必要ではありません。
なお、部署マスタテーブル「MS_DEPT」には、有効開始日、有効終了日があります。
例：
部署ID　有効開始日　有効終了日　部署名
0001       2020/1/1       2020/12/31    部署名A
0001       2021/1/1       2021/12/31    部署名B

テーブルAの一覧を取得するとき（部署名を含む）、SQLは下記のようになります。
```
select
a.*,
b.部署名
where
a 
lert outer join MS_DEPT b on
b.dept_id = a.dept_id
パラメータ.日付 between b.有効開始日 and b.有効終了日
where
....................
```

**Comment by nakamura-to** [comment]
次のバージョンで、今のwhere句で指定できる条件と同等のものをon句でも指定できるようにしたいと思います。

**Comment by gikeihi** [comment]
早速のご対応、ありがとうございました！
