### ISSUE TITLE
SQL ファイルを使用する update が実行されない (Doma 2.3)

### ISSUE THREAD

**Issue by OdaShinsuke** [domaframework/doma#78]
2.2 から 2.3 にバージョンを上げたところ、第一引数が Entity では無い、SQL ファイルを利用する update が SKIP されるようになりました。

```
情報: [DOMA2223] SKIP   : クラス=[hoge.dao.HogeDaoImpl], メソッド=[updateHoge], 理由=[STATE_UNCHANGED]
```

update のメソッドの第一引数が Entity のものは、「更新カラムリスト生成コメント」を使用しない場合でも実行されています。

**Comment by nakamura-to** [comment]
報告ありがとうございます。
再現できました。
