### ISSUE TITLE
Version number spec is different from the document

### ISSUE THREAD

**Issue by bufferings** [domaframework/doma#85]
Hi,

There's a difference when the version = 0.
Document or implementation should be corrected.

The document says:
http://doma.readthedocs.org/ja/stable/query/insert/#id5

> エンティティクラス に @Version が注釈されたプロパティがある場合、 そのプロパティに明示的に 1 以上の値が設定されていればその値を使用します。 もし設定されていないか、 0 以下の値が設定されていれば 1 を自動で設定します。

But actual implementation seems:
https://github.com/domaframework/doma/blob/8d03e94d713c6548c12c4c41aeb744ecf915d012/src/main/java/org/seasar/doma/jdbc/entity/VersionPropertyType.java#L118

```
        @Override
        public <V extends Number> Boolean visitNumberWrapper(
                NumberWrapper<V> wrapper, Number value, Void q) {
            Number currentValue = wrapper.get();
            if (currentValue == null || currentValue.intValue() < 0) {
                wrapper.set(value);
                return true;
            }
            return false;
        }
```

Doma version1 has the same issue.

**Comment by nakamura-to** [comment]
Thank you.

I will fix the document.
