### ISSUE TITLE
Criteria APIにて、タプルを使ったIN述語を3項目以上で使用する方法を教えてほしい

### ISSUE THREAD

**Issue by mazeneko** [domaframework/doma#860]
Java17でPostgreSQL 12へのDBアクセスをするために、 バージョン`2.51.1`のDomaでCriteria APIを使用しています。

3項目以上の複合主キーを持ったテーブルをselectする際に、

```sql
select * from some_table t0_
where (t0_.item1, t0_.item2, t0_.item3) in ((?, ?, ?), (?, ?, ?))
```

のようなSQLを発行したいと思っています。

[Doma入門 - Criteria API チートシート](https://qiita.com/nakamura-to/items/04def9dc3d218d50c71f#in:~:text=t0_.age%20in%20(%3F%2C%20%3F)-,%E3%82%BF%E3%83%97%E3%83%AB%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9FIN%E8%BF%B0%E8%AA%9E%E3%80%82,-entityql.from)の`タプルを使ったIN述語`で例示されているコードがそれにあたると思うのですが、 `ComparisonDeclaration`クラスの`in`メソッドで`Tuple3`~`Tuple9`を引数に取るものがなさそうでしたので、 タプルを使ったIN述語は`Tuple2`のみ対応していると認識しました。

Criteria APIで前述の目標を達成する方法はありますか？

**Comment by nakamura-to** [comment]
残念ながら現在サポートしているのは`Tuple2`のみです。
3項目以上を受け取るIN句をCriteria APIで生成することはできないです。

**Comment by nakamura-to** [comment]
補足すると、IN句に相当する条件をOR句を使って表現することはできます。
次のように別メソッドに定義して再利用してもいいかもしれません。

3項目のIN句をエミュレートするメソッド:
```java
    static <A, B, C> void in3(WhereDeclaration c,
                  Tuple3<PropertyMetamodel<A>, PropertyMetamodel<B>, PropertyMetamodel<C>> properties,
                  Tuple3<A, B, C> values) {
        c.and(() -> {
            c.or(() -> c.eq(properties.getItem1(), values.getItem1()));
            c.or(() -> c.eq(properties.getItem2(), values.getItem2()));
            c.or(() -> c.eq(properties.getItem3(), values.getItem3()));
        });
    }
```

呼び出し側:
```
        Employee_ e = new Employee_();

        List<Employee> list =
                entityql
                        .from(e)
                        .where(c -> in3(c, new Tuple3<>(e.id1, e.id2, e.id3), new Tuple3<>(1, 2, 3)))
                        .fetch();

        assertEquals(3, list.size());
```

**Comment by mazeneko** [comment]
解説ありがとうございます。
IN句は使用せずに代替の方法を使用することにします。

余談ですが、
やりたかったことは複合主キーのテーブルからのID指定でのレコード取得でしたので、
例示していただいていたソースとは違って
```java
Employee_ e = new Employee_();
Set<EmployeeId> ids = Set.of(
    new EmployeeId(1, 2, 3),
    new EmployeeId(1, 2, 4),
    new EmployeeId(2, 2, 3));

List<Employee> list = entityql
    .from(e)
    .where(c -> {
      ids.forEach(id -> {
        c.or(() -> {
          c.eq(e.id1, id.id1);
          c.eq(e.id2, id.id2);
          c.eq(e.id2, id.id3);
        });
      });
    })
    .fetch();

assertEquals(3, list.size());
```
のように実装しました。
