### ISSUE TITLE
MySQLでSelectOptioinsでlimit 0を指定するとlimit 0, 18446744073709551615のSQLが作成される

### ISSUE THREAD

**Issue by h-yokoyama** [domaframework/doma#866]
**Describe the bug**
Daoインターフェースで@SelectでSelectOptionsを検索をしています。
`limit 0`を指定すると生成されるSQLが`limit 0, 18446744073709551615`となります。

サンプルコード
``` HogeDao.java
    @Select
    List<Hoge> find(Query query, SelectOptions option);
```
```
    hogeDao.find(query, SelectOptions.get().offset(0).limit(0);
```
MySQLの[ドキュメント](https://dev.mysql.com/doc/refman/5.6/ja/select.html)によるとlimit句に指定できる数値は`どちらも負ではない整定数である必要があります。`(実際に `select * from hoge limit 0, 0`のSQLはMySQLでは実行可能)とのことですので、limit 0を指定できるようにご検討いただけませんでしょうか。もしくはlimit 0の場合にlimitの上限を変換している意図がございましたらご教示いただけないでしょうか。

**Expected behavior**
`limit 0, 0`のSQLが生成される

**Actual behavior**
`limit 0, 18446744073709551615`のSQLが作成される

**To Reproduce**
1.DaoインターフェースでSelectOptionsのlimitに0を指定する

**Environment (please complete the following information):**
- Doma version or git rev: 2.50.0
- IDE version (ie. Eclipse or IntelliJ IDEA): IntelliJ IDEA 2021.2.2(Ultimate Edition)
- Output of `java -version`: openjdk version "1.8.0_292"
- Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.5.4
- Database version: MySQL5.6
- JDBC Driver version: mysql-connector-java-8.0.29

**Comment by nakamura-to** [comment]
> limit 0の場合にlimitの上限を変換している意図

Oracle DatabaseやSQL Serverなど他のデータベースと挙動を合わせるためです。これらのデータベースではMySQLの`limit 0`に相当する挙動が定義されていないので、Domaでは`limit 0`は全件取得と同じ挙動をとるように調整されています。

> limit 0を指定できるようにご検討いただけませんでしょうか

この挙動に依存しているアプリがあるかもしれないので、もし対応するにしても互換性の維持は重要視したいと考えています。

### ワークアラウンドの案

`limit 0`を許容したいのは空の結果セットを得たいからだと想像します。 `limit`に渡す値で条件分岐して値が`0`のときはSQLのWHERE句が `WHERE 1 = 0` のようになるように調整していただければ期待する結果を得られると思います。

**Comment by h-yokoyama** [comment]
>>limit 0の場合にlimitの上限を変換している意図

>Oracle DatabaseやSQL Serverなど他のデータベースと挙動を合わせるためです。これらのデータベースではMySQLのlimit 0に相当する挙動が定義されていないので、Domaではlimit 0は全件取得と同じ挙動をとるように調整されています。

こちら回答いただきありがとうございます。理解いたしました。
提示いただいたワークアラウンド案での検討をしたいと思います。
