### ISSUE TITLE
OriginalState comparing BigDecimal by using equals 

### ISSUE THREAD

**Issue by orlandokj** [domaframework/doma#925]
**Describe the bug**
When I have a BigDecimal field in my entity and I have original state to avoid updating unchanged fields, the comparision between the original BigDecimal value and the new BigDecimal value is made using `.equals` method, but with BigDecimal this doesn't always work.

In the screenshot in the section below we can see that when the comparision is made, "0" and "0.00" is different to BigDecimal using equals. But if we use `.compareTo` it returns 0 meaning that they are equals.

**Expected behavior**
BigDecimal fields should be compared by `compareTo` method.

**Actual behavior**
BigDecimal fields are compared using `equals` method, which can be false even if the values are equals numericly

**To Reproduce**
Steps to reproduce the behavior (Using MySQL database):
1. Create an entity with a BigDecimal field (type decimal(10, 2) on database) and with @OriginalStates field
2. The original BigDecimal value always come with decimal places, even if the number is exact (0.00), if we set the same value for the entity without decimal places (0) and update the entity it will dispatch an update command to database, even if nothing changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/8892300/221202426-a3f9a15e-9a8b-494f-9102-1f0fe604fdf9.png)

**Environment (please complete the following information):**
- Doma version or git rev: 1.7.0
- IDE version (ie. Eclipse or IntelliJ IDEA): 2022.3.2
- Output of `java -version`: 
      openjdk version "17.0.2" 2022-01-18
      OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
      OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
- Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.8.6 
- Database version: MySQL 8.0.28
- JDBC Driver version: mysql-connector-j:8.0.32

**Additional context**
By looking at the sources, I think the fix may be simple: 
Override the method `doHasEqualValue` in the class `BigDecimalWrapper` and then compare the values using `compareTo` method. But I am just starting using Doma and do not have the knowledge to know when the BigDecimalWrapper is used, so I didn't created a PR.

English is a second language for me, so if I was not clear, let me know and I will try to explain it differently.

**Comment by nakamura-to** [comment]
Thank you for the detailed report.
This fix will be released in the next version.
