### ISSUE TITLE
埋め込み変数コメントの展開後にスペースを挿入しないで欲しい

### ISSUE THREAD

**Issue by chibat** [domaframework/doma#95]
お世話になっております。
千葉です。

埋め込み変数コメントが展開された後にスペースが挿入されるようなのですが、挿入されないように修正頂けないでしょうか？

SQLファイルが以下の場合、
```sql
select * from /*#envPrefix*/SCHEMA.TABLE
```
envPrefix="STG_" が展開されると以下のようになります。
```sql
select * from STG_ SCHEMA.TABLE
```
期待する結果としては以下です。
```sql
select * from STG_SCHEMA.TABLE
```

以上、ご検討のほど宜しくお願い致します。

**Comment by nakamura-to** [comment]
対応完了しました。
もし必要であればSNAPSHOTをつかってお試しいただけます。

**Comment by chibat** [comment]
ご対応ありがとうございます！
確認してみます。

**Comment by chibat** [comment]
確認OKでした。
ありがとうございます！

**Comment by nakamura-to** [comment]
:+1:
