### ISSUE TITLE
バッチ挿入のパフォーマンスが悪い

### ISSUE THREAD

**Issue by tasuku-s** [domaframework/doma#98]
PostgreSQLにて、id列に`@GeneratedValue(strategy = GenerationType.IDENTITY)`
をつけたエンティティのバッチ挿入を行う場合、
idをエンティティにセットしなければならない関係上`preparedStatement`を使いまわしてくれず、
かつ1件挿入のたびにidを取得しにいってしまうようです。

バッチ挿入のユースケースでは、idのセットは必要でないことが多いため、
idセットを行うかどうかをDaoで制御できればよいなと思いました。

加えて、事前にidを取得できるDBであれば、
使うidを事前に予約しておくことでSQL発行回数を減らせると考えています。

 
例えばPostgreSQLであれば 
```sql
select nextval('hoge_id_seq') from generate_series(1, 1000)
```
のように取得できます

**Comment by nakamura-to** [comment]
対応しましたが、Daoでの制御（アノテーションによる制御）は入れていません。
PostgreSQLで `@GeneratedValue(strategy = GenerationType.IDENTITY)` を使っていてバッチ挿入であれば、常に事前にidを確保するようにしました。アノテーションで制御したいユースケースが思い浮かばなかったからです。

**Comment by tasuku-s** [comment]
おおー、そちらの機能があれば十分です！
ありがとうございます！
